### ISSUE TITLE
Text scale changes when text_right exceeds some length

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#1332] opened 2021-03-31 07:39 UTC
1. version [x.y.z, hash, other]: https://github.com/Motion-Project/motion/commit/34091a770c679da79f5be58f392020a8514521ee

This has been reported on the mail list: https://sourceforge.net/p/motion/mailman/message/37140031/

When text_right or text_left are exceeding some length the scale value gets decreased dynamically causing overlay'ed text to "jump"

The issue could not be reproduced with the user's config for some reason. But manually increasing the length of the variable allowed to reproduce it locally:
```
text_left CAMERA1
text_right %D \naaaaaaaaaaaaaaaadddaaaaaaaaaaaaaaaaaaa%K,%L \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n%N \n%Y-%m-%d %T-%q\n%{fps}\n\n
text_scale 2
```
https://user-images.githubusercontent.com/3600973/113107984-2f41be80-920d-11eb-9d8d-a857c85c85c1.mp4

[motion-text-wrap.txt](https://github.com/Motion-Project/motion/files/6234671/motion-text-wrap.txt)

This needs to be investigated whether this is a feature or a bug

**Comment by Mr-DaveDev** [comment] 2021-04-16 02:44
This is certainly possible but it is unclear as to how the code could be changed.  

For example, if the text is illustrating the changed pixels.  In that situation the number of pixel changes could be anywhere from one character to seven(?).  Now when setting the text_scale at a number such as three, the text may just barely fit in the allotted space and look great.   But now once the pixel changes so that it is four or five digits, the text will no longer fit into the allotted space and therefore the scale has to be reduced to 2 in order for it to fit.  

Now, in theory for the example above the maximum size of the pixel changes could be determined and therefore it would not permit a scale of greater than 2.  But that would be a unique situation and it would not work for the infinite possibilities of what could be placed into the text parameters.

**Comment by tosiara** [comment] 2021-04-16 12:13
Maybe truncate the text which does not fit on the screen with the given scale?

**Comment by Mr-DaveDev** [comment] 2021-04-20 04:22
I think the chopping it off would be a much worse option than changing the scaling.

**Comment by Mr-Dave** [comment] 2021-07-31 02:31
Closing.  This is working exactly like it was intended.

**Closed by Mr-Dave** 2021-07-31 02:31 UTC
Labels: bug
