### ISSUE TITLE
mystrftime is working not as expected, needs better handling of percent symbol

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#1264] opened 2020-11-19 12:34 UTC
1. version [x.y.z, hash, other]: https://github.com/Motion-Project/motion/commit/dc670f5da977465241171fd01dcfc6713f49d8f2

1 .

The following `text_right a%25b` specifier generates `alapkr.` result, where `lapkr.` seems to be a short localized name of the current month in Lithuiania (my current) region (full name is Lapkritis):

![image](https://user-images.githubusercontent.com/3600973/99666149-41e40400-2a73-11eb-9f00-55b8fd0ba558.png)

While a user would expect to get `a%25b` as there is no such specifier like `%2` or `%b`

2 .

A `text_right a% b` specifier generates `a  b`, missing the `%` symbol:

![image](https://user-images.githubusercontent.com/3600973/99666274-748dfc80-2a73-11eb-86bf-c03b29b95e01.png)

3 .

`text_right %` gives empty output, missing `%` symbol. So, currently there is no way to output a percent symbol

The function needs to be revised to correctly handle all the valid cases.

I suggest to fully move to `{specifier}` format, but still support old one-symbol specifiers with a notice that support will be dropped at some time.

Reference to user list: https://sourceforge.net/p/motion/mailman/message/37154829/

**Comment by Mr-Dave** [comment] 2020-11-20 02:31
I do not understand why this was tagged as a bug since Motion has never supported special characters.  

This seems like a duplicate of #1231.  And as indicated #1231 that is really pretty much the same as #1082

**Comment by tosiara** [comment] 2020-11-20 13:46
This issue is not related to any other special chars. There is only an issue with processing the percent symbol.

According to this line: https://github.com/Motion-Project/motion/blob/master/src/util.c#L562 is there was not specifier match the percent symbol and the byte following should be passed as is. If this is not true, and `%` is not a supported one, then that code line has confused me.

But what about `a%25b`? Why does it produce a weird output? Shouldn't it output `a 25b`?

**Comment by Mr-Dave** [comment] 2020-11-21 02:16
OK.  To me, all these are special characters and fall into the same category as #1231 .  The % symbol is just one more of them except that it is tougher to implement than the rest.  

As for a%25b, it would be "a" and then the abbreviation of "lapkričio mėn" for you.  And for me it is an "a" and then the abbreviation of "November" for me....i.e. C seems to interpret the 25 as a width or length specifier that is ignored on `%b` (abbreviated month) specifier.

**Comment by tosiara** [comment] 2020-11-21 17:11
But `%b` is not documented. I could add more missing specifier to doc PR. How did you find that %b is an "abbreviated month"?

And would you accept a PR with more symbols added to `draw.c`, like here: https://github.com/Motion-Project/motion/issues/1231#issuecomment-731192669

**Comment by Mr-Dave** [comment] 2020-11-21 23:07
`%b` is documented.  Per the Motion guide on [conversion specifiers](https://motion-project.github.io/motion_config.html#conversion_specifiers) 

>  In addition to the above, the conversion specifiers include the same options as for the C function strftime (3)

then  the `strftime(3)` manual [page](https://man7.org/linux/man-pages/man3/strftime.3.html)

If you want to build the symbols in a PR, I will push it in.

**Closed** 2020-11-24 09:10 UTC
Labels: bug, duplicate
