### ISSUE TITLE
ffmpeg_passthrough segfault

### ISSUE THREAD

**Issue by j-m-baker** [Motion-Project/motion#610] opened 2018-01-09 08:48 UTC
Hello,

I've cloned motion from master December 2017 and built on an x86 platform:

Linux laptop 4.8.0-59-generic #64-Ubuntu SMP Thu Jun 29 19:38:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I've noticed that motion segfaults when running with passthrough enabled, and works correctly without passthrough enabled. I've run it in gdb and here is the crash:

Thread 12 "nc8:Drive" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbe390700 (LWP 26016)]
0x00007ffff7904711 in av_buffer_unref ()
  from /usr/lib/x86_64-linux-gnu/libavutil.so.55

The output of thread info and a backtrace from all threads attached.

John
[gdb.txt](https://github.com/Motion-Project/motion/files/1614410/gdb.txt)

**Comment by Mr-Dave** [comment] 2018-01-09 14:31
In order for me to try to reproduce it, lots of questions.

1.  Does it always occur?  
2.  Do you have a log at INF level?  
3.  How many cameras were there?
4.  How many packets were reported as added to the buffer?  
5.  Fast machine or particularly slow machine?
6.  Any network issues that precede the crash

Most of the above questions can be seen in the log at the INF level.

**Comment by j-m-baker** [comment] 2018-01-11 07:53
Hello,

1. Yes, without fail. Switch passthrough on and it fails usually within a few hours. Switch off and it runs for days as it should.
2. Yes although it doesn't say anything useful that I wouldn't expect if running without passthruogh.
4. Where do I find this information?
5. Decent, four core, with about two being used.
6. None.

**Comment by Mr-Dave** [comment] 2018-01-11 14:02
I put out a PR for one issue but based upon the responses, I can't determine whether it would be applicable to what you are observing.  The PR addresses a lost connection / reconnect situation in which the new packet array is  smaller than the previous one.  But if there wasn't any network issues that caused the camera to disconnect and then go into reconnect mode, this situation would not apply.  

The packet array size will be in the log when specified at the `INF` level and will report a line such as 
`[1:ml1] [INF] [NET] netcam_rtsp_pktarray_resize: High resolution: Resized packet array to 122`
and since the array is specific to each camera the log has to be reviewed to determine what was the last size reported for that camera before the disconnect and what was the size it established after it reconnected.

**Comment by Mr-Dave** [comment] 2018-01-13 00:26
Are you able to test with the latest change pushed to the repo?  It has been running on my setup without issue for two days now.  If it does fail on your setup, we will need to be provided with the log at the INF level so I can see your configuration options and replicate them on my system.

**Comment by j-m-baker** [comment] 2018-01-14 20:29
Will do

**Comment by j-m-baker** [comment] 2018-01-16 09:03
Working great. Must have been a camera disconnecting (I've got some hot plugs involved). I do notice this:

SIGVTALRM went off

**Comment by Mr-Dave** [comment] 2018-01-17 00:07
The SIGVTALRM could be many different things but this issue with the segfault seems to be resolved so closing this issue.

**Closed by Mr-Dave** 2018-01-17 00:07 UTC
