### ISSUE TITLE
CMake can't find ffmpeg libs during linkage

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#257] opened 2016-11-15 08:22 UTC
Steps to repro:

1. git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg
2. cd ffmpeg 
3. ./configure --prefix=/home/odroid/git/ffmpeg/out
4. make -j3
5. make install
6. cd ../motion/
7. PKG_CONFIG_PATH=/home/odroid/git/ffmpeg/out/lib/pkgconfig cmake .
8. make

```
[ 91%] Building C object CMakeFiles/motion.dir/vloopback_motion.c.o
[ 95%] Building C object CMakeFiles/motion.dir/webhttpd.c.o
[100%] Linking C executable motion
/usr/bin/ld: cannot find -lavformat
/usr/bin/ld: cannot find -lavcodec
/usr/bin/ld: cannot find -lswresample
/usr/bin/ld: cannot find -lswscale
/usr/bin/ld: cannot find -lavutil
/usr/bin/ld: cannot find -lavcodec
/usr/bin/ld: cannot find -lswresample
/usr/bin/ld: cannot find -lswscale
/usr/bin/ld: cannot find -lavutil
collect2: error: ld returned 1 exit status
CMakeFiles/motion.dir/build.make:669: recipe for target 'motion' failed
make[2]: *** [motion] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/motion.dir/all' failed
make[1]: *** [CMakeFiles/motion.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by tosiara** [comment] 2016-11-15 08:23
Could be blocked by CMake upstream bug: https://gitlab.kitware.com/cmake/cmake/issues/16154#note_188104

**Comment by slokhorst** [comment] 2016-11-15 10:45
What distro are you using? So I can try to repro it.

**Comment by tosiara** [comment] 2016-11-15 12:41
Tested openSUSE 42 and Ubuntu 16

**Comment by slokhorst** [comment] 2016-11-16 15:05
I really don't understand what's going on.. I can't reproduce this on a fresh Ubuntu 16.04 install (with #254 applied):

````bash
sudo apt install git cmake yasm libjpeg-dev
git clone https://github.com/FFmpeg/FFmpeg.git ~/ffmpeg
cd ~/ffmpeg
./configure --prefix=/home/sebas/ffinstall
make
make install
git clone https://github.com/Motion-Project/motion.git ~/motion
cd ~/motion
git fetch origin pull/254/head:254 #required fix
git checkout 254 #required fix
PKG_CONFIG_PATH=/home/sebas/ffinstall/lib/pkgconfig cmake .
make
````

Works just fine... Same thing on Debian and Arch Linux.

**Comment by jogu** [comment] 2016-11-16 15:09
@slokhurst is there any chance your way ended up with the ffinstall folder added to the default linker path somewhere? I'm thinking of something like /etc/ld.so.conf, but I'm not sure that's read when gcc runs the link step.

The other possibility might be that your's and @tosiara's pkgconfig file are different, perhaps one has absolute paths and one relative paths or something - perhaps you could both stick your ffmpeg pkgconfig into gist and add a link here?

**Comment by tosiara** [comment] 2016-11-16 15:19
No, my pkgconfig are using full path

@slokhorst maybe your default install already delivers ffmpeg libs somewhere?
Can you try to search, like this:
```
$ sudo find / | grep libavformat | grep -v "/home/odroid/git/ffmpeg"
/var/lib/dpkg/info/libavformat-ffmpeg56:armhf.md5sums
/var/lib/dpkg/info/libavformat-ffmpeg56:armhf.symbols
/var/lib/dpkg/info/libavformat-ffmpeg56:armhf.triggers
/var/lib/dpkg/info/libavformat-ffmpeg56:armhf.list
/var/lib/dpkg/info/libavformat-ffmpeg56:armhf.shlibs
/var/cache/apt/archives/libavformat-ffmpeg56_7%3a2.8.8-0ubuntu0.16.04.1_armhf.deb
/usr/lib/arm-linux-gnueabihf/libavformat-ffmpeg.so.56.40.101
/usr/lib/arm-linux-gnueabihf/libavformat-ffmpeg.so.56
/usr/lib/vlc/plugins/demux/libavformat_plugin.so
/usr/share/doc/libavformat-ffmpeg56
/usr/share/doc/libavformat-ffmpeg56/changelog.Debian.gz
/usr/share/doc/libavformat-ffmpeg56/copyright
/usr/share/lintian/overrides/libavformat-ffmpeg56
```

**Comment by slokhorst** [comment] 2016-11-16 15:19
I highly doubt it. This is a fresh Ubuntu install (I ran literally *nothing* before those commands). All the commands, except for the first *apt*, were run as my non-root user.

The only thing I can think of is that something incorrect is stored in CMake's cache. That might happen when the fix was applied *after* running `cmake` for the first time. @tosiara: can you, after you make sure the patch is applied, run `rm -r CMakeCache.txt CMakeFiles` in the motion directory, and then run `PKG_CONFIG_PATH=/home/odroid/git/ffmpeg/out/lib/pkgconfig cmake . && make` again?

**Comment by tosiara** [comment] 2016-11-16 15:31
Copied exact your commands - and it worked. I guess the problem was that I forgot to apply the patch :)
Tested one more time, checked out current master - and linkage fails. So the pull https://github.com/Motion-Project/motion/pull/254 resolves the issue, lets merge it

**Comment by slokhorst** [comment] 2016-11-16 15:45
@tosiara, great that it's working now! :)

**Comment by jogu** [comment] 2016-11-16 15:52
Awesome! Thanks both. I've merged it.

**Closed** 2016-11-17 15:56 UTC
Labels: enhancement
