### ISSUE TITLE
Incorrect handling of file handles in exec related functions

### ISSUE THREAD

**Issue by CRCinAU** [Motion-Project/motion#1478] opened 2022-03-13 02:42 UTC
Re: https://github.com/Motion-Project/motion/blob/2645d6706b20a78a86b3427059b75704bbd532e9/src/event.c#L102

In tracking down this problem:
https://github.com/Motion-Project/motion/discussions/1477

I stumbled across the documentation[1] for `execl()`, and it shows that line probably should be:

```
execl("/bin/sh", "sh", "-c", stamp, " &", (char *)0);
```

In fact, for proper usage, it would be useful to also capture the return code to see if it was successful - ie:

```
int ret;
ret = execl("/bin/sh", "sh", "-c", stamp, " &", (char *)0);
```

I'm not exactly what you'd get as a return code, but it might be more useful for troubleshooting.

Right now, I'm not quite able to understand why I'm getting 100% CPU usage - like a for loop / while is not exiting on the forked thread..... but I haven't been able to identify it yet.

1: https://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html

**Comment by CRCinAU** [comment] 2022-03-13 03:03
As a further reference, it is likely that some of the file handling could be reviewed with the following guidelines:
https://wiki.sei.cmu.edu/confluence/display/c/FIO22-C.+Close+files+before+spawning+processes

**Comment by CRCinAU** [comment] 2022-03-13 03:44
A bit more info - I managed to get strace hooked to the looping process, and I'm getting:

```
close(18569941)                         = -1 EBADF (Bad file descriptor)
close(18569940)                         = -1 EBADF (Bad file descriptor)
close(18569939)                         = -1 EBADF (Bad file descriptor)
close(18569938)                         = -1 EBADF (Bad file descriptor)
close(18569937)                         = -1 EBADF (Bad file descriptor)
close(18569936)                         = -1 EBADF (Bad file descriptor)
close(18569935)                         = -1 EBADF (Bad file descriptor)
```

That's looping forever. Given that the numbers are decreasing, I'm wondering if its related to:
https://github.com/Motion-Project/motion/blob/master/src/event.c#L98

**Comment by Mr-Dave** [comment] 2022-03-14 05:09
Is the issue resolved by changing the count?  i.e. The problem is that loop on closing.

**Comment by CRCinAU** [comment] 2022-03-14 05:55
I wouldn't say that it is resolved - however by changing the ulimit on the number of file handles allowed, therefore a lower number being returned by `getdtablesize()` stops the process spawned by `execl()` from iterating from a massive number.

In the case of ulimit being set to 1024, then `getdtablesize()` will only return 1024. Likely, the file handles should be opened with the `FD_CLOEXEC` attribute - so there would be no need to close open handles in the forked process.

The link in comment https://github.com/Motion-Project/motion/issues/1478#issuecomment-1066011409 shows the usage of `fnctl` to set the flags on a filehandle.

**Comment by Mr-Dave** [comment] 2022-03-25 03:30
It is indicated as the topic "incorrect handling of file handles" and the comments also indicate to use `FD_CLOEXEC`.   

Within the code, Motion is setting the open flags as `O_CLOEXEC` and reviewing internet search results, this seems to be the preferred implementation method.  

Perhaps you can comment on why it would be better to use `FD_CLOEXEC` in a separate step rather than `O_CLOEXEC` upon open.  (Or correct my understanding of the difference between them)

**Comment by CRCinAU** [comment] 2022-03-25 04:22
The insides of C aren't my speciality - which makes things kinda hard - but I'll try to get some feedback from people that know C sooo much better than me...

If, when the `execl()` is called, filehandles are automatically closed, would this mean that explicitly closing all file handles returned via `getdtablesize()` is actually not required?

If that's the case, then just removing that code would fix the issue I was observing - however if it kept the file handles open after doing the `execl()`, then would that just lead to more issues?

**Closed** 2022-06-12 23:57 UTC
