### ISSUE TITLE
memchr usage

### ISSUE THREAD

**Issue by slokhorst** [Motion-Project/motion#183] opened 2016-09-22 14:27 UTC
I don't use C very often, so I'm not sure about this, but I think there is a error [webhttp.c#L2467](https://github.com/Motion-Project/motion/blob/1d74158bce48ca99a618fb698de51e1e2d034430/webhttpd.c#L2467):
````C
char *colon = memchr(hostname, ':', hostname-end_host);
`````

Where (I think) `char* hostname` is the start of the hostname and `char* end_host` is the end of the hostname.

So the length of the hostname should be `end_host-hostname`. However the opposite of that is used (`hostname-end_host`).

**Comment by jogu** [comment] 2016-09-24 08:09
Whoops. Yes. Quite right. Only worked because it almost always found a : I guess, but certainly not what was intended :)

**Comment by jogu** [comment] 2016-09-24 08:26
Fixed by https://github.com/Motion-Project/motion/issues/182 - thanks!

**Closed by jogu** 2016-09-24 08:26 UTC
