### ISSUE TITLE
Requesting Snapshot via URL produces no output

### ISSUE THREAD

**Issue by vitaminrad** [Motion-Project/motion#735] opened 2018-06-20 19:52 UTC
Running Motion 4.1.1+git20180614-57944cd on Ubuntu 16.04 in daemon mode.  Compiled from GIT.

Camera stream is RTSP.

Using the snapshot url ( http://X.X.X.X:8080/0/action/snapshot ) does not produce a JPEG in target directory.

Setting `snapshot_interval` to integer produces snapshot images.

Output from cURL request:

```
curl -v http://172.19.10.10:8080/0/action/snapshot
Trying 172.19.10.10...
Connected to 172.19.10.10 (172.19.10.10) port 8080 (#0)
GET /0/action/snapshot HTTP/1.1
Host: 172.19.10.10:8080
User-Agent: curl/7.47.0
Accept: */*

HTTP/1.1 200 OK
Server: Motion /4.1.1+git20180614-57944cd
Connection: close
Max-Age: 0
Expires: 0
Cache-Control: no-cache
Cache-Control: private
Pragma: no-cache
Content-type: text/html

Closing connection 0
```

**Comment by genius3000** [comment] 2018-06-20 20:37
What is your `webcontrol_interface ` set to? It needs to be `1` (text format) for direct URL (curl) use. If that's correct, please try a snapshot on the individual thread(s) and see if that works.

**Comment by vitaminrad** [comment] 2018-06-20 20:52
Thanks for the quick response - I've changed `webcontrol_interface` to 1 (text format) and still no luck.

I'm using an IP camera using h.264 encoding with two streams `netcam_url` and `netcam_highres`.

**Comment by genius3000** [comment] 2018-06-20 22:31
Hmmm, I stand corrected; it will accept the direct URL for a snapshot even in CSS/HTML mode (value of `0`). I ran the exact same command as you tried and got the exact same response but it did produce snapshots for each camera. Same version/git hash.  
Can you run with log level at INF/7, try the curl command, and then paste that log to a Gist or Pastebin (or similar). I can try to reproduce this with a full scope view. It's strange that it will produce snapshots from the config directive but not the Web command, as they use the same internal function.

**Comment by vitaminrad** [comment] 2018-06-20 22:51
I really appreciate your help.  Please find below the link to the gist containing my motion.log (after restart and requesting two snapshots via URL and one via cURL.

[https://gist.github.com/vitaminrad/7675594f8eb2f2149455a7bb50913f1c](https://gist.github.com/vitaminrad/7675594f8eb2f2149455a7bb50913f1c)

**Comment by vitaminrad** [comment] 2018-06-20 22:56
I upped the log_level to 9 and this is what I see after requesting a snapshot:

```
[0:wu0] [DBG] [STR] [Jun 20 15:54:16] webu_parseurl: Sent url: /0/action/snapshot
[0:wu0] [DBG] [STR] [Jun 20 15:54:16] webu_parseurl: Decoded url: /0/action/snapshot
[0:wu0] [DBG] [STR] [Jun 20 15:54:16] webu_parseurl: thread: >0< cmd1: >action< cmd2: >snapshot< parm1:>< val1:>< parm2:>< val2:><
[0:wu0] [INF] [STR] [Jun 20 15:54:16] webu_httpd_run: Read from client (192.168.44.220) 0
```

**Comment by genius3000** [comment] 2018-06-20 23:47
Traced down the issue, it's a bug in the code. Simply put, the code to handle calls to `thread 0` (at least within `webu_process_action`) assume thread 0 is just the Motion thread and any cameras are on subsequent threads. By using just the one configuration file (`motion.conf`) you run on a single thread for both Motion and the camera. The code skips over thread 0 (due to it's assumption) and ends there, as there's no more threads.  

If you want to do a quick code patch, I can provide the details of that for you; but the easier/better method until a proper patch is merged would be to split your camera to it's own thread. Basically just take anything that is camera specific (`camera_id`, `camera_name`, `netcam_*` should do it for now) and put those into a `camera1.conf` (or name it better). You can then include that in the `motion.conf` by the `camera ...` line or the `camera_dir` line (the latter simplifying things if you start setting up multiple cameras). Be sure to remove or comment out the `netcam_url` (and probably the highres one too) in `motion.conf` after or it may try duplicating things. This way thread 0 will be Motion and thread 1 will be the camera, allowing `.../0/action/snapshot` to work.

**Comment by vitaminrad** [comment] 2018-06-20 23:59
You sir, are a scholar and a gentleman.  Thanks for your help today!

**Closed** 2018-06-22 01:38 UTC
Labels: bug
