### ISSUE TITLE
Mac OS X Installation: missing CMAKElists.txt

### ISSUE THREAD

**Issue by happicamper** [Motion-Project/motion#483] opened 2017-08-31 01:42 UTC
1. version [x.y.z, hash, other]: latest 4.0.1, master branch
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: webcam (USB)
5. hardware [x86, ARM, other]: x64
6. operating system [Linux (which), FreeBSD, other]: Mac OS X 10.11.6

Hello, I just want to ask if what is the recommended installation method should I use to install motion on my OS X machine because as I reviewed some changes, you guys removed the creation or something related to **cmake**. 
Maybe that's the cause of the error I'm experiencing:
`$motion_dir does not appear to contain CMakeLists.txt.`

I've tried using ffmpeg but still on the method : 
`PKG_CONFIG_PATH=$home/git/ffmpeg/out/lib/pkgconfig cmake .`
which leads me again to an error related to **CmakeLists.txt**.

Any help will be appreciated, thank you very much!

**Comment by Mr-Dave** [comment] 2017-08-31 03:46
There no method that I am aware of that I can test a Mac build.  The tools historically listed for a Mac build include "autoconf-2.57 or above" and "make-3.79 or above"  The building has been confirmed on a FreeBSD platform with gmake.

**Comment by Mr-Dave** [comment] 2017-09-02 20:58
Closing this issue since the travis test environment is indicating that the above procedure works.  We will be creating / tracking a new issue for updating the documentation and guide to properly indicate how to build on OS X.

**Closed by Mr-Dave** 2017-09-02 20:58 UTC

**Comment by happicamper** [comment] 2017-09-06 01:01
Will look forward to the guide on how to install on OS X. Thanks, @Mr-Dave!

**Comment by Mr-Dave** [comment] 2017-09-06 02:40
It is not much different than the other build instructions...

brew upgrade ffmpeg
brew upgrade pkg-config
brew upgrade jpeg
brew install ffmpeg pkg-config libjpeg
autoreconf -fiv
./configure
make
make install

**Comment by happicamper** [comment] 2017-09-06 03:03
Hi @Mr-Dave, I'm experiencing error:
```autoreconf -fiv         
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /opt/boxen/homebrew/Cellar/autoconf/2.69/bin/autoconf --force
autoreconf: running: /opt/boxen/homebrew/Cellar/autoconf/2.69/bin/autoheader --force
autoreconf: configure.ac: not using Automake
autoreconf: Leaving directory `.'
```
Are you familiar somehow with this? I can't proceed to `./configure` because it isn't present. Maybe the command `autoreconf -fiv` generates that? 
I'm not limiting the fact that it maybe because of my commands is at the path `/opt/boxen`? 
Your time is very much appreciated.

**Comment by Mr-Dave** [comment] 2017-09-06 03:26
The commands need to be run within the Motion directory which has the code.  You may want to review the travis build log for Apple to see if anything jumps out.  [Log](https://travis-ci.org/Motion-Project/motion/jobs/272270853)
