### ISSUE TITLE
Watchdog timeout with passthrough

### ISSUE THREAD

**Issue by j-m-baker** [Motion-Project/motion#619] opened 2018-01-18 10:09 UTC
Using motion from trunk with ffmpeg_passthrough. Why did it do this:

[3:ml3:Drive] [NTC] [ALL] [Jan 17 02:30:48] motion_detected: Motion detected - starting event 579
[3:ml3:Drive] [NTC] [ALL] [Jan 17 02:31:19] preview_save: different filename or picture only!
[3:ml3:Drive] [NTC] [EVT] [Jan 17 02:31:19] event_newfile: File of type 1 saved to: /data/cameras/active/drive/pictures/2018-01-17/023048-03.jpg
[3:ml3:Drive] [NTC] [ALL] [Jan 17 02:31:19] mlp_actions: End of event 579
[14:nc14:Drive2] [ERR] [NET] [Jan 17 02:38:54] netcam_rtsp_handler: Normal resolution: Bad image.  Reconnecting with camera....
[14:nc14:Garden] [ERR] [NET] [Jan 17 02:38:55] netcam_rtsp_handler: Normal resolution: Bad image.  Reconnecting with camera....
[0:motion] [ERR] [ALL] [Jan 17 02:39:29] main: Thread 6 - Watchdog timeout, trying to do a graceful restart
[0:motion] [ERR] [ALL] [Jan 17 02:39:29] main: Thread 7 - Watchdog timeout, trying to do a graceful restart
[0:motion] [ERR] [ALL] [Jan 17 02:40:29] main: Thread 6 - Watchdog timeout, did NOT restart graceful, killing it!
[0:motion] [ERR] [ALL] [Jan 17 02:40:29] main: Thread 7 - Watchdog timeout, did NOT restart graceful, killing it!
[0:motion] [ERR] [ALL] [Jan 17 02:40:31] main: cleaning Thread 6
[0:motion] [NTC] [STR] [Jan 17 02:40:31] stream_stop: Closing motion-stream listen socket & active motion-stream sockets
[0:motion] [NTC] [STR] [Jan 17 02:40:31] stream_stop: Closed motion-stream listen socket & active motion-stream sockets
[0:motion] [ERR] [NET] [Jan 17 02:40:41] netcam_rtsp_cleanup: Normal resolution: No response from handler thread.
[0:motion] [NTC] [NET] [Jan 17 02:40:41] netcam_rtsp_cleanup: Normal resolution: Shut down complete.

**Comment by j-m-baker** [comment] 2018-01-18 10:10
Oh, it segfaulted. I'll get a trace.

**Comment by j-m-baker** [comment] 2018-01-18 10:24
[Thread 0x7fffd5ffb700 (LWP 1725) exited]
[Thread 0x7fffd7fff700 (LWP 1721) exited]
[Thread 0x7fff807f9700 (LWP 1778) exited]
[Thread 0x7fff7fff8700 (LWP 1779) exited]
[Thread 0x7fff80ffa700 (LWP 1777) exited]

Thread 1 "motion" received signal SIGSEGV, Segmentation fault.
__pthread_kill (threadid=140736783693568, signo=0) at ../sysdeps/unix/sysv/linux/pthread_kill.c:39
39      ../sysdeps/unix/sysv/linux/pthread_kill.c: No such file or directory.

[gdb.txt](https://github.com/Motion-Project/motion/files/1642449/gdb.txt)

**Comment by Mr-DaveDev** [comment] 2018-01-18 14:55
I think these are different.  The segfault looks like #366  which I have been unable to reproduce on any of my computers.  The first issue would be trying to determine what caused it to become non-responsive to begin with before it goes into a watchdog timeout.  I will need to be provided with the log at the INF level to see the setup.

**Comment by j-m-baker** [comment] 2018-01-18 15:21
Do you want the log as it starts up? Or whilst running for some time?

**Comment by Mr-Dave** [comment] 2018-01-20 02:12
It would be best to see the full log at the INF level so that I can create the same setup on one of my computers as well as possibly see the sections before the bad image and lock to see what Motion was doing.  Post to a gist or if preferred send directly.  The information in the log should be redacted unless the ffmpeg libs are reporting something.

**Comment by j-m-baker** [comment] 2018-01-20 13:55
I enabled pasthrough, started the process and ran for a few seconds, then quit.
[motion.log](https://github.com/Motion-Project/motion/files/1648856/motion.log)

**Comment by j-m-baker** [comment] 2018-01-24 13:02
Do you require more information to diagnose?

**Comment by Mr-Dave** [comment] 2018-01-25 04:49
The log is sufficient for the moment.  I have not however been able to reproduce the watchdog timeout / lock nor the segfault on restart shutdown with my rtsp cameras,   As such, it could take some time to resolve this.

**Comment by forgi007** [comment] 2018-01-26 22:40
I have the same issue (Watchdog timeout with passthrough), but Only in daemon mode. I am on Ubuntu mate with rtsp cam. I have built motion yesterday from git master branch.

See logs below, first with daemon off, second is from syslog in daemon mode. Please let me know if I can help any further.

motion
[0:Unknown] [NTC] [ALL] conf_load: Processing thread 0 - config file /home/pi/motion.conf
[0:Unknown] [NTC] [ALL] motion_startup: Logging to syslog
[0:Unknown] [NTC] [ALL] motion_startup: Motion 4.1+git20171110-ccbe2f5 Started
[0:Unknown] [NTC] [ALL] motion_startup: Using log type (ALL) log level (NTC)
[0:Unknown] [NTC] [ENC] ffmpeg_global_init: ffmpeg libavcodec version 56.60.100 libavformat version 56.40.101
[0:Unknown] [NTC] [ALL] main: Camera ID: 0 is from /home/pi/motion.conf
[0:Unknown] [NTC] [ALL] main: Camera ID: 0 Camera Name: (null) Service: rtsp:
[0:Unknown] [NTC] [ALL] main: Stream port 8081
[0:Unknown] [NTC] [ALL] main: Waiting for threads to finish, pid: 3386
[1:Unknown] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
[1:Unknown] [NTC] [VID] vid_start: Opening Netcam RTSP
[0:Unknown] [NTC] [STR] http_bindsock: listening on 127.0.0.1 port 8080
[0:Unknown] [NTC] [STR] httpd_run: Started motion-httpd server on port 8080 (auth Disabled)
[1:Unknown] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera ((null)) connected
[1:Unknown] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
[3:Unknown] [NTC] [NET] netcam_rtsp_handler: Normal resolution: Camera handler thread [3] started
[3:Unknown] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera ((null)) connected
[1:Unknown] [NTC] [STR] http_bindsock: listening on any IPv4 address port 8081
[1:Unknown] [NTC] [ALL] motion_init: Started motion-stream server on port 8081 (auth Disabled)
^[[B^[[B[1:Unknown] [NTC] [ENC] ffmpeg_passthru_codec: pass-through mode enabled.  Changing to MP4 container.
[1:Unknown] [NTC] [EVT] event_newfile: File of type 8 saved to: /mnt/disk1/cam1/01-20180126233216.mp4
[1:Unknown] [NTC] [ALL] motion_detected: Motion detected - starting event 1
[1:Unknown] [NTC] [ALL] mlp_actions: End of event 1

#############################################################
# daemon on, syslog
#############################################################
Jan 26 23:09:23 bpi-iot-ros-ai motion[578]:  * Starting motion detection daemon : motion
Jan 26 23:09:23 bpi-iot-ros-ai motion[578]:    ...done.
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] conf_load: Processing thread 0 - config file /usr/local/etc/motion/motion.conf
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] motion_startup: Logging to syslog
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] motion_startup: Motion 4.1+git20171110-ccbe2f5 Started
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] motion_startup: Using log type (ALL) log level (NTC)
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] become_daemon: Motion going to daemon mode
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] become_daemon: Created process id file /home/pi/motion/motion.pid. Process ID is 796
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] motion_startup: Motion running as daemon process
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ENC] ffmpeg_global_init: ffmpeg libavcodec version 56.60.100 libavformat version 56.40.101
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] main: Camera ID: 0 is from /usr/local/etc/motion/motion.conf
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] main: Camera ID: 0 Camera Name: (null) Service: rtsp:
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] main: Stream port 8081
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] main: Waiting for threads to finish, pid: 796
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [STR] http_bindsock: listening on 127.0.0.1 port 8080
Jan 26 23:09:31 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [STR] httpd_run: Started motion-httpd server on port 8080 (auth Disabled)
Jan 26 23:09:31 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
Jan 26 23:09:31 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [VID] vid_start: Opening Netcam RTSP
Jan 26 23:09:31 bpi-iot-ros-ai motion: [1:Unknown] [ERR] [NET] netcam_rtsp_open_context: Normal resolution: Unable to open camera((null)): Network is unreachable
Jan 26 23:09:31 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [NET] netcam_rtsp_cleanup: Normal resolution: Shut down complete.
Jan 26 23:09:31 bpi-iot-ros-ai motion: [1:Unknown] [ERR] [VID] vid_start: Netcam RTSP failed to open
Jan 26 23:09:31 bpi-iot-ros-ai motion: [1:Unknown] [WRN] [ALL] motion_init: Could not fetch initial image from camera
Jan 26 23:09:31 bpi-iot-ros-ai motion: [1:Unknown] [WRN] [ALL] motion_init: Motion continues using width and height from config file(s)
Jan 26 23:09:31 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
Jan 26 23:09:32 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [STR] http_bindsock: listening on any IPv4 address port 8081
Jan 26 23:09:32 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [ALL] motion_init: Started motion-stream server on port 8081 (auth Disabled)
Jan 26 23:09:40 bpi-iot-ros-ai motion: [1:Unknown] [WRN] [ALL] mlp_retry: Retrying until successful connection with camera
Jan 26 23:09:40 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [VID] vid_start: Opening Netcam RTSP
Jan 26 23:09:45 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera ((null)) connected
Jan 26 23:09:45 bpi-iot-ros-ai motion: [3:Unknown] [NTC] [NET] netcam_rtsp_handler: Normal resolution: Camera handler thread [3] started
Jan 26 23:10:45 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: Thread 1 - Watchdog timeout, trying to do a graceful restart
Jan 26 23:11:45 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: Thread 1 - Watchdog timeout, did NOT restart graceful, killing it!
Jan 26 23:15:22 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: cleaning Thread 1
Jan 26 23:15:22 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [STR] stream_stop: Closing motion-stream listen socket & active motion-stream sockets
Jan 26 23:15:22 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [STR] stream_stop: Closed motion-stream listen socket & active motion-stream sockets
Jan 26 23:15:32 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [NET] netcam_rtsp_cleanup: Normal resolution: No response from handler thread.
Jan 26 23:15:32 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [NET] netcam_rtsp_cleanup: Normal resolution: Shut down complete.
Jan 26 23:15:33 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] main: Motion thread 1 restart
Jan 26 23:15:33 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
Jan 26 23:15:33 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [VID] vid_start: Opening Netcam RTSP
Jan 26 23:15:36 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera ((null)) connected
Jan 26 23:15:37 bpi-iot-ros-ai motion: [3:Unknown] [NTC] [NET] netcam_rtsp_handler: Normal resolution: Camera handler thread [3] started
Jan 26 23:15:37 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
Jan 26 23:16:02 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: Thread 1 - Watchdog timeout, trying to do a graceful restart
Jan 26 23:17:02 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: Thread 1 - Watchdog timeout, did NOT restart graceful, killing it!
Jan 26 23:17:04 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: cleaning Thread 1
Jan 26 23:17:14 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [NET] netcam_rtsp_cleanup: Normal resolution: No response from handler thread.
Jan 26 23:17:14 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [NET] netcam_rtsp_cleanup: Normal resolution: Shut down complete.
Jan 26 23:17:15 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] main: Motion thread 1 restart
Jan 26 23:17:15 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
Jan 26 23:17:15 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [VID] vid_start: Opening Netcam RTSP
Jan 26 23:17:19 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera ((null)) connected
Jan 26 23:17:19 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
Jan 26 23:17:19 bpi-iot-ros-ai motion: [3:Unknown] [NTC] [NET] netcam_rtsp_handler: Normal resolution: Camera handler thread [3] started
Jan 26 23:17:44 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: Thread 1 - Watchdog timeout, trying to do a graceful restart
Jan 26 23:18:44 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: Thread 1 - Watchdog timeout, did NOT restart graceful, killing it!
Jan 26 23:18:46 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: cleaning Thread 1
Jan 26 23:18:56 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [NET] netcam_rtsp_cleanup: Normal resolution: No response from handler thread.
Jan 26 23:18:56 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [NET] netcam_rtsp_cleanup: Normal resolution: Shut down complete.
Jan 26 23:18:57 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] main: Motion thread 1 restart
Jan 26 23:18:57 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
Jan 26 23:18:57 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [VID] vid_start: Opening Netcam RTSP
Jan 26 23:19:01 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera ((null)) connected
Jan 26 23:19:01 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
Jan 26 23:19:01 bpi-iot-ros-ai motion: [3:Unknown] [NTC] [NET] netcam_rtsp_handler: Normal resolution: Camera handler thread [3] started
Jan 26 23:19:26 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: Thread 1 - Watchdog timeout, trying to do a graceful restart
Jan 26 23:20:26 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: Thread 1 - Watchdog timeout, did NOT restart graceful, killing it!
Jan 26 23:20:28 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: cleaning Thread 1
Jan 26 23:20:38 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [NET] netcam_rtsp_cleanup: Normal resolution: No response from handler thread.
Jan 26 23:20:38 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [NET] netcam_rtsp_cleanup: Normal resolution: Shut down complete.
Jan 26 23:20:39 bpi-iot-ros-ai motion: [0:Unknown] [NTC] [ALL] main: Motion thread 1 restart
Jan 26 23:20:39 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
Jan 26 23:20:39 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [VID] vid_start: Opening Netcam RTSP
Jan 26 23:20:43 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera ((null)) connected
Jan 26 23:20:43 bpi-iot-ros-ai motion: [1:Unknown] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
Jan 26 23:20:43 bpi-iot-ros-ai motion: [3:Unknown] [NTC] [NET] netcam_rtsp_handler: Normal resolution: Camera handler thread [3] started
Jan 26 23:21:08 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: Thread 1 - Watchdog timeout, trying to do a graceful restart
Jan 26 23:22:08 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: Thread 1 - Watchdog timeout, did NOT restart graceful, killing it!
Jan 26 23:22:10 bpi-iot-ros-ai motion: [0:Unknown] [ERR] [ALL] main: cleaning Thread 1

**Comment by forgi007** [comment] 2018-01-26 23:12
I do not have the issue with git 631200a928f2a481707d30dfebadba2d77b8b5f8. I suspect the error with later versions might be related with having several instances of motion running in parallel (at least in my case, during playing with the settings in /etc/init.d/motion).

**Comment by Mr-DaveDev** [comment] 2018-01-27 01:19
I appreciate seeing the log but think that this is different.  This log shows the network is unreachable which throws it into the loop waiting forever to it to come back up.  Also, the version of Motion that created the above log did not include the pass through changes and therefore can not be related to the change.  (The version indicated in the log is Motion 4.1+git20171110-ccbe2f5)

**Comment by j-m-baker** [comment] 2018-02-08 08:08
Mr-DaveDev: Anything else we can do to help you diagnose this issue?

**Comment by Mr-Dave** [comment] 2018-02-08 13:22
I really need the full log from start to the crash/timeout at the INF level from your cameras.  I thought if I let my cameras run on this for a few days it would occur but so far, I've had this running for 2 weeks 24x7 with multiple disconnect/reconnects and it has not had either.

**Comment by j-m-baker** [comment] 2018-03-04 07:41
Any of this help?
[6:ml6:Drive2] [NTC] [ENC] [Mar 04 01:31:26] ffmpeg_passthru_codec: pass-through mode enabled.  Changing to MP4 container.
[6:ml6:Drive2] [NTC] [EVT] [Mar 04 01:31:26] event_newfile: File of type 8 saved to: /data/cameras/active/drive2/motion/2018-03-04/013125.mp4
[6:ml6:Drive2] [NTC] [ALL] [Mar 04 01:31:26] motion_detected: Motion detected - starting event 2
[14:nc14:Garden] [ERR] [NET] [Mar 04 01:32:29] netcam_rtsp_handler: Normal resolution: Bad image.  Reconnecting with camera....
[6:ml6:Drive2] [NTC] [ALL] [Mar 04 01:32:43] preview_save: different filename or picture only!
6:ml6:Drive2] [NTC] [EVT] [Mar 04 01:32:43] event_newfile: File of type 1 saved to: /data/cameras/active/drive2/pictures/2018-03-04/013139-02.jpg
[6:ml6:Drive2] [NTC] [ALL] [Mar 04 01:32:43] mlp_actions: End of event 2
[14:nc14:Drive2] [ERR] [NET] [Mar 04 01:32:49] netcam_rtsp_handler: Normal resolution: Bad image.  Reconnecting with camera....
[0:motion] [ERR] [ALL] [Mar 04 01:33:03] main: Thread 7 - Watchdog timeout, trying to do a graceful restart
[0:motion] [ERR] [ALL] [Mar 04 01:33:25] main: Thread 6 - Watchdog timeout, trying to do a graceful restart
[3:ml3:Drive] [NTC] [ENC] [Mar 04 01:33:34] ffmpeg_passthru_codec: pass-through mode enabled.  Changing to MP4 container.
[3:ml3:Drive] [NTC] [EVT] [Mar 04 01:33:34] event_newfile: File of type 8 saved to: /data/cameras/active/drive/motion/2018-03-04/013333.mp4
[3:ml3:Drive] [NTC] [ALL] [Mar 04 01:33:34] motion_detected: Motion detected - starting event 158
[2:ml2:Patio] [NTC] [ENC] [Mar 04 01:33:46] ffmpeg_passthru_codec: pass-through mode enabled.  Changing to MP4 container.
[2:ml2:Patio] [NTC] [EVT] [Mar 04 01:33:46] event_newfile: File of type 8 saved to: /data/cameras/active/patio/motion/2018-03-04/013346.mp4
[2:ml2:Patio] [NTC] [ALL] [Mar 04 01:33:46] motion_detected: Motion detected - starting event 134
[0:motion] [ERR] [ALL] [Mar 04 01:34:03] main: Thread 7 - Watchdog timeout, did NOT restart graceful, killing it!
[0:motion] [ERR] [ALL] [Mar 04 01:34:05] main: cleaning Thread 7
[0:motion] [NTC] [STR] [Mar 04 01:34:05] stream_stop: Closing motion-stream listen socket & active motion-stream sockets
[0:motion] [NTC] [STR] [Mar 04 01:34:05] stream_stop: Closed motion-stream listen socket & active motion-stream sockets
[0:motion] [ERR] [NET] [Mar 04 01:34:15] netcam_rtsp_cleanup: Normal resolution: No response from handler thread.
[0:motion] [NTC] [NET] [Mar 04 01:34:15] netcam_rtsp_cleanup: Normal resolution: Shut down complete.
[0:motion] [NTC] [ALL] [Mar 04 01:34:16] main: Motion thread 7 restart
[7:ml7:Garden] [NTC] [ALL] [Mar 04 01:34:16] motion_init: Camera 7 started: motion detection Enabled
[7:ml7:Garden] [NTC] [VID] [Mar 04 01:34:16] vid_start: Opening Netcam RTSP
[3:ml3:Drive] [NTC] [ALL] [Mar 04 01:34:17] preview_save: different filename or picture only!
[3:ml3:Drive] [NTC] [EVT] [Mar 04 01:34:17] event_newfile: File of type 1 saved to: /data/cameras/active/drive/pictures/2018-03-04/013346-04.jpg
[3:ml3:Drive] [NTC] [ALL] [Mar 04 01:34:17] mlp_actions: End of event 158
[7:ml7:Garden] [NTC] [NET] [Mar 04 01:34:21] netcam_rtsp_connect: Normal resolution: Camera (Garden) connected
[7:ml7:Garden] [NTC] [ALL] [Mar 04 01:34:21] image_ring_resize: Resizing pre_capture buffer to 1 items
[14:nc14:Garden] [NTC] [NET] [Mar 04 01:34:21] netcam_rtsp_handler: Normal resolution: Camera handler thread [14] started
[14:nc14:Garden] [NTC] [NET] [Mar 04 01:34:25] netcam_rtsp_connect: Normal resolution: Camera (Garden) connected
[7:ml7:Garden] [NTC] [STR] [Mar 04 01:34:25] http_bindsock: listening on any IPv4 address port 9006
[7:ml7:Garden] [NTC] [ALL] [Mar 04 01:34:25] motion_init: Started motion-stream server on port 9006 (auth Disabled)
[7:ml7:Garden] [NTC] [ALL] [Mar 04 01:34:25] image_ring_resize: Resizing pre_capture buffer to 3 items
[7:ml7:Garden] [NTC] [EVT] [Mar 04 01:34:25] event_ffmpeg_timelapse: Timelapse using mpeg4 codec.
[7:ml7:Garden] [NTC] [EVT] [Mar 04 01:34:25] event_ffmpeg_timelapse: Events will be trigger new files
[7:ml7:Garden] [NTC] [EVT] [Mar 04 01:34:25] event_newfile: File of type 32 saved to: /data/cameras/active/garden/timelapse/2018-03-04.0134-timelapse.avi
[0:motion] [ERR] [ALL] [Mar 04 01:34:35] main: Thread 6 - Watchdog timeout, did NOT restart graceful, killing it!
[0:motion] [ERR] [ALL] [Mar 04 01:34:37] main: cleaning Thread 6
[0:motion] [NTC] [STR] [Mar 04 01:34:37] stream_stop: Closing motion-stream listen socket & active motion-stream sockets
[0:motion] [NTC] [STR] [Mar 04 01:34:37] stream_stop: Closed motion-stream listen socket & active motion-stream sockets
[0:motion] [ERR] [NET] [Mar 04 01:34:47] netcam_rtsp_cleanup: Normal resolution: No response from handler thread.
[0:motion] [NTC] [NET] [Mar 04 01:34:47] netcam_rtsp_cleanup: Normal resolution: Shut down complete.
[0:motion] [NTC] [ALL] [Mar 04 01:34:48] main: Motion thread 6 restart
[6:ml6:Drive2] [NTC] [ALL] [Mar 04 01:34:48] motion_init: Camera 6 started: motion detection Enabled
[6:ml6:Drive2] [NTC] [VID] [Mar 04 01:34:48] vid_start: Opening Netcam RTSP
[6:ml6:Drive2] [NTC] [NET] [Mar 04 01:34:54] netcam_rtsp_connect: Normal resolution: Camera (Drive2) connected
[6:ml6:Drive2] [NTC] [ALL] [Mar 04 01:34:54] image_ring_resize: Resizing pre_capture buffer to 1 items
[14:nc14:Drive2] [NTC] [NET] [Mar 04 01:34:54] netcam_rtsp_handler: Normal resolution: Camera handler thread [14] started
[14:nc14:Drive2] [NTC] [NET] [Mar 04 01:35:00] netcam_rtsp_connect: Normal resolution: Camera (Drive2) connected
[6:ml6:Drive2] [NTC] [STR] [Mar 04 01:35:02] http_bindsock: listening on any IPv4 address port 9005
[6:ml6:Drive2] [NTC] [ALL] [Mar 04 01:35:02] motion_init: Started motion-stream server on port 9005 (auth Disabled)
[6:ml6:Drive2] [NTC] [ALL] [Mar 04 01:35:02] image_ring_resize: Resizing pre_capture buffer to 3 items

Then it core dumped.

**Comment by Mr-DaveDev** [comment] 2018-03-05 00:24
No.  This is not a full log nor is it at the INF level.

**Comment by Mr-Dave** [comment] 2018-03-14 02:36
The latest pulls "may" help the recovery from a `Watchdog` but I'm still unable to reproduce a lockup in normal mode which I view as the root issue.

**Comment by miffels** [comment] 2018-03-28 21:25
FWIW - just had the same issue (segfault, watchdog timeout) and I found the issue was a badly connected MMAL cam.

**Comment by Mr-Dave** [comment] 2018-06-06 23:07
Closing as unable to reproduce after latest changes.

**Comment by bol-van** [comment] 2018-06-29 11:52
No, its still happening. Same issue with 1 RTSP camers in passthru mode.

**Comment by Mr-Dave** [comment] 2018-06-29 12:36
I would like it demonstrated by providing a full uncut log at the INF level.

**Comment by bol-van** [comment] 2018-06-29 13:12
It happens rarely. I configured log level to 7 and will post log when it crashes

**Comment by bol-van** [comment] 2018-06-29 13:15
It happened very quickly after I cut power from camera so It unexpectedly gone and rebooted
https://pastebin.com/LAusQntq

**Comment by bol-van** [comment] 2018-06-29 13:53
It happens every time I force reboot camera.

This repeats very fast :

[2:Unknown] [INF] [ENC] [Jun 29 16:50:46] ffmpeg_avcodec_log: Connection to tcp://cam-hall.lan:554?timeout=0 failed: Connection refused
[2:Unknown] [INF] [ENC] Above message repeats 492 times

I can make changes to the code and run it if you wish

**Comment by bol-van** [comment] 2018-06-29 13:56
During excessive retries it queries camera host DNS  hunderds of times

> 
> 16:55:18.774643 IP 192.168.2.7.49936 > 192.168.2.7.53: 26443+ A? cam-hall.lan. (30)
> 16:55:18.774695 IP 192.168.2.7.49936 > 192.168.2.7.53: 27307+ AAAA? cam-hall.lan. (30)
> 16:55:18.775448 IP 192.168.2.7.53 > 192.168.2.7.49936: 26443* 1/0/0 A 192.168.253.250 (46)
> 16:55:18.775703 IP 192.168.2.7.53 > 192.168.2.7.49936: 27307 0/0/0 (30)
> 16:55:18.776680 IP 192.168.2.7.47609 > 192.168.2.7.53: 35667+ A? cam-hall.lan. (30)
> 16:55:18.776709 IP 192.168.2.7.47609 > 192.168.2.7.53: 36255+ AAAA? cam-hall.lan. (30)
> 16:55:18.777498 IP 192.168.2.7.53 > 192.168.2.7.47609: 35667* 1/0/0 A 192.168.253.250 (46)
>

**Comment by forgi007** [comment] 2018-06-29 17:58
Hi,

Thank you for following this. Here is an uncut log attached (forgot to send
it earlier).

regards,
Tamas

2018. jún. 29. du. 2:36 ezt írta ("Mr-Dave" <notifications@github.com>):

I would like it demonstrated by providing a full uncut log at the INF level.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Motion-Project/motion/issues/619#issuecomment-401341321>,
or mute the thread

**Comment by Mr-DaveDev** [comment] 2018-06-29 23:53
Thanks @bol-van , it really helps getting a full log so I have an idea of how to recreate and where to look.  @forgi007 , there was no log attached to your response so I will be unable to assist in any issue you are observing.

**Comment by Mr-DaveDev** [comment] 2018-06-30 01:36
I have created PR #744 which should address some of the locks/watchdogs when recovering from lost cameras.

**Comment by forgi007** [comment] 2018-06-30 09:31
Hi,

Sorry, here is the log attached.

BR,
Tamas
​
 motion.log
<https://drive.google.com/file/d/0B8NUjh7oOnuuYllWVERPX0ZfYkR2X2pXMDE4NFF1Z3RYak8w/view?usp=drive_web>
​

2018-06-30 1:53 GMT+02:00 Mr-DaveDev <notifications@github.com>:

**Comment by Mr-Dave** [comment] 2018-06-30 14:59
@forgi007 can you try the PR?  Your log seems to show it locking at the same point.

**Comment by forgi007** [comment] 2018-06-30 15:21
I will try the PR thank you. But I can do it only at the end of next week.

BR,
Tamas

Mr-Dave <notifications@github.com> ezt írta (időpont: 2018. jún. 30., Szo
16:59):

**Closed** 2018-07-09 03:44 UTC
