### ISSUE TITLE
[Enhancement Request] Support PIR sensors in cameras

### ISSUE THREAD

**Issue by joergent** [Motion-Project/motion#1200] opened 2020-09-13 18:56 UTC
Some cameras have a passive infrared sensor (PIR sensor) e.g. the Logitech Brio Ultra HD Pro Webcam. I suggest, that motion should have support for motion detection also by these PIR sensors. As the input is not from some external device, but from the camera, which motion already is communicating with, it must be a much simpler task to implement.

**Comment by tosiara** [comment] 2020-09-14 08:13
Is it a duplicate? https://github.com/Motion-Project/motion/issues/596

**Comment by joergent** [comment] 2020-09-14 09:06
Not really. #596 is wandering into dealing with external PIR sensors. I just want motion to act on a PIR signal which the camera raises in the protocol already communicating with the camera instead of motion ignoring it. It is just a motion detection without looking at the image.  In case of the Logitech BRIO there is a SDK for Windows describing the protocol.

**Comment by tosiara** [comment] 2020-09-14 09:08
Please clarify, you want your Camera to send signal to motion when there is motion detected?

**Comment by joergent** [comment] 2020-09-14 10:28
The motion program already has a connection to the camera through which it is setting and reading parameters. 
Once the camera is detecting motion, it may indicate this by setting a parameter and/or by issuing an interrupt to the controlling program. Whether this program is detecting the PIR event by polling the camera or by catching an interrupt from it, must be dependent on the combination of the program and the camera.
The motion program has already a lot of logic handling the detection of motion. This request is just about handling motion detection already done by a PIR sensor in the camera thus circumventing the image comparison part when this event occurs. There are more and more cameras in the marketplace incorporating a PIR sensor.

**Comment by tosiara** [comment] 2020-09-14 11:07
> motion detection already done by a PIR sensor

So why do you think this is not a duplicate of a request https://github.com/Motion-Project/motion/issues/596 which wants to add a support for external PIR (gpio or camera)?

**Comment by joergent** [comment] 2020-09-14 11:25
As I already mentioned:
"#596 is wandering into dealing with external PIR sensors" 
It is much more complex to connect separate units with separate communication channels than adding functionality to an existing communication channel to a unit already connected.

**Comment by tosiara** [comment] 2020-09-14 11:33
Which `existing communication channel` do you mean? Is it `V4L2`?

**Comment by joergent** [comment] 2020-09-15 18:13
I am not a developer of motion. 
I am a long time user of motion, but also an IT-professional describing the design and implementation of a new feature as I see it.
I have no idea about exactly which protocols are in play.

**Closed** 2020-09-16 06:49 UTC
Labels: duplicate
