### ISSUE TITLE
Add a format specifier for hostname in mystrftime

### ISSUE THREAD

**Issue by pascal-fb-martin** [Motion-Project/motion#299] opened 2017-01-14 19:07 UTC
I run motion on multiple small computers (FriendlyARM NanoPi NEO) with a USB cam on each, feeding a file server through NFS. Each computer acts as a motion-powered network camera.

I found that the most convenient way to organize the video is by date and time, independently of the camera. I add a unique camera ID (in my case: host name + ':' + %t) to avoid any possible name conflicts. (Note that a camera ID is not necessarily a user-friendly name, only a guaranteed-to-be-unique name.)

As of today, I write the host name explicitly in motion.conf, which is a pain because most of my motion.conf files are quasi the same. Having a format specifier for the host name would help. Considering that all alphabetical characters are used, I would propose to use "%@" (@ chosen by reference to emails and ssh). The code to handle this new modifier in mystrftime:
            `case '@': // host name`
                `gethostname (tempstr,PATH_MAX);`
                `tempstring[PATH_MAX-1] = 0; // See man page for gethostname.`
               ` break;`
(I discovered the recently added %$ camera name option while researching for this submission. I am not sure yet about using a user-friendly name (with spaces?) as a discriminant in a file name. I prefer a ID to not change easily.)

**Comment by tosiara** [comment] 2017-01-15 11:48
Why not use a string from confg file? Set camera name to include hostname, like `NanoPi1-camera2`, and use it.

Additionally, I would recommend you not to write directly to a network share (smb or nfs). This may cause corrupted video files if link becomes unstable. Instead you can write locally and write a script that is ran on video finish and may copy file asynchronously or rename to whatever you like

**Comment by pascal-fb-martin** [comment] 2017-01-15 14:39
As noted, I discovered the %$ modifier while looking at adding the host name. This is one possibility. There are two reasons why I would prefer the host name + camera number combination:
- Using the proposed %@, the config file is the same for two different machines. It adjusts automatically. Besides the apparent simplicity, this also participates in making the unique property more reliable.
- The camera name seems more intended for display (e.g. "backyard", "porch", etc.) I have learned to beware user-defined display names as unique ID, as I have seen plenty of cases when the user's preferences lead to non-unique ID, strings containing characters not compatible with file names (use '/'?) and scripts (space?), or when user changes lead to horrifically complicated cases to handle. A unique ID should not change easily. The benefit of the host name is that this is already a well understood unique ID, with common rules compatible with file names.

Another (related) point is that using the camera name as part of a file name restricts what set of characters the user can include. So this would also lead to (possibly annoying) user restrictions on the camera name side.

Regarding use of NFS: my main concern if that if I store the video locally, and then transfer to a server, I will likely kill the microSD card that the NanoPi runs on (large volume of write). The server is on a wired 1 Gb Ethernet, the NanoPi are on a 100Mb Ethernet switch hooked to the same 1 Gb Ethernet. I use automount for NFS (to survive power outage, when the reboot order is not well specified). There is no WiFi being used.

An alternative would be to save on RAM (tmpfs), then copy. Since I have the 512MB version of the NanoPi, this should work (largest files generated so far: 74MB, RAM available per "free": 438MB). I will be more comfortable if I have a way to manage the limited space, through. Any advice?

**Comment by pascal-fb-martin** [comment] 2017-01-15 14:47
Please note that I have not yet tested my proposed code change. I need to setup a patched motion on a test environment, which may take me a few days.

**Comment by slokhorst** [comment] 2017-01-15 15:35
The network file writing is pretty unrelated.. If you have a stable network and it works, then why not.

I think adding this option is a good idea. Like @pascal-fb-martin said, it's definitely useful for mass-deploying motion, and I can't really see any downsides.

**Comment by Mr-Dave** [comment] 2017-01-15 15:42
The issue is there are virtually no additional options for specifiers remaining.  With there only being a few options remaining, I would like to save what we have left for items that can not be determined externally.  This would be for things such as pixel changes, location of motion, etc.  

If anyone has an idea on how to allow for more total options for the specifier so we are not limited, then I'd be more open.

**Comment by slokhorst** [comment] 2017-01-15 15:50
@Mr-Dave I had not realised that. Maybe we could add another sign besides `%` to add additional specifiers? Or maybe introduce something like `%_x` where `x` can be a new specifier?

**Comment by tosiara** [comment] 2017-01-15 16:42
To overcome current limitation we will need to change existing template parsing logic and move to something like `{PARAM1}` or `%PARAM2%`

**Comment by tosiara** [comment] 2017-01-15 16:44
However, there are already working examples, like `%fps` https://github.com/Motion-Project/motion/blob/master/motion.c#L3341

**Comment by pascal-fb-martin** [comment] 2017-01-15 19:44
I have used the following syntax in multiples cases: { keyword } (e.g.
"{hostname}"). If having to make character { a special one is an issue, the
variant below is also possible and might reduce code impact too:

% { keyword }

The use of balanced limits is quite important: the end of the modifier is
known even if the keyword is not supported. This make the analysis code
more robust.

I have no problem dropping %@ and use something long like %{hostname}. I
will gladely take the length hit for better readability. If nobody has any
fundamental issue with that alternative, i am actually motivated to
implement the change in mystrftime and post code (will do a pull request if
too long for a post).

Thanks.

**Comment by Mr-Dave** [comment] 2017-01-15 20:10
Sounds good on the change to the format specifier.  This will also allow us to have a more robust method for handing future revisions.

**Comment by tosiara** [comment] 2017-01-16 13:52
@pascal-fb-martin and regarding your statement

> if I store the video locally, and then transfer to a server, I will likely kill the microSD card that the NanoPi runs on (large volume of write)

I have bunch of different ARM devices running motion in this mode. Write locally, upload to a fileserver and rotate files (delete oldest first). Using cheapest microSD cards. The oldest camera is running on Rikomagic MK802 since 2012 (4+ years!)

**Comment by pascal-fb-martin** [comment] 2017-01-16 16:33
@tosiara interesting comment about Rikomagic. My nanopi NEO with a 1.2GHz H3 is >50% CPU usage all the time, and it appears that there are seemingly irregular frame losses during recording. I suspect CPU being overloaded. Any tuning advice? (Sorry for changing subject.)

**Comment by tosiara** [comment] 2017-01-17 20:57
It depends how much cpu is used by the motion main thread. If it is close to 100%  you will experience frame drop. Two things are important:
1. input frame must be raw (avoid mjpeg decoding)
2. using `extpipe` (to offload video encoding to other cpu cores)
I have been able to achieve max 720p@4fps on OrangePi (similar to NanoPi NEO). But it is too close to the limit. So ended up using 800x600@8fps

**Comment by Mr-Dave** [comment] 2017-01-19 03:56
closed via pull request #301

**Closed by Mr-Dave** 2017-01-19 03:56 UTC
Labels: enhancement, In Progress
