### ISSUE TITLE
Flush codec at the end of a recording

### ISSUE THREAD

**Issue by jasaw** [Motion-Project/motion#492] opened 2017-09-04 02:13 UTC
1. version [x.y.z, hash, other]: 9f4f0e99dc50b13d339f3bc9273e80a2308e6f5b
2. installed as a package or compiled from sources [deb, rpm, git, other]: compiled from source
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: only tested with v4l2 & mmal
5. hardware [x86, ARM, other]: only tested on ARM
6. operating system [Linux (which), FreeBSD, other]: only tested on Linux

Some encoders like H264 encoders (tested with h264_omx) buffer up multiple frames before outputting a single encoded packet. Motion currently does not "flush" the codec, resulting in the recorded video being cut short.

According to ffmpeg documentation:
> End of stream situations. These require "flushing" (aka draining) the codec, as the codec might buffer multiple frames or packets internally for performance or out of necessity (consider B-frames). This is handled as follows:
>
> - Instead of valid input, send NULL to the avcodec_send_packet() (decoding) or avcodec_send_frame() (encoding) functions. This will enter draining mode.
> - Call avcodec_receive_frame() (decoding) or avcodec_receive_packet() (encoding) in a loop until AVERROR_EOF is returned. The functions will not return AVERROR(EAGAIN), unless you forgot to enter draining mode.

**Comment by jasaw** [comment] 2017-09-08 15:21
I've implemented codec draining on my branch and initial tests show that recorded videos are not being cut short anymore. 
Motion really needs to drain the codec.

**Comment by ccrisan** [comment] 2017-09-08 20:10
@jasaw given the relatively large number of motionEye(OS) users that have complained in the past about this issue (including myself), can we have a motionEyeOS-specific motion patch for this particular issue until (if) this gets fixed in motion/master?

**Comment by Mr-Dave** [comment] 2017-09-12 01:27
I have merged the setting of the pts to the frames so we can now add a new drain function.  

I would add however that I have tested the various containers and do not see this as having a big impact.  Definitely nothing as dramatic as what was reported in the issues here or on MotionEye.  For all the containers a sample 600 second movie was recorded and they resulted in lengths of either 9:59 or 10:00 so it looks like we may be missing 1 second.  

If there is concern about the length of the movies being cutoff, I'd recommend turning on the `emulate_motion` parameter to determine whether it is related to the encoding routines or whether it has to do with the `post_capture` setting.  e.g. If the movie length is correct after setting `emulate_motion` parameter, then the issue is with the parameter used for `post_capture`.

**Comment by jasaw** [comment] 2017-09-12 01:54
@Mr-Dave Before the codec drain fix, I could reproduce the cut-short-by-minutes problem by using `emulate_motion` and `max_movie_time`, and h264_omx encoder. `post_capture` was off. I think MotionEye "continuous capture" mode does the same thing internally, where the issue was first observed and reported.

From what I've observed, it appears that h264_omx encoder does more buffering than libx264 encoder, which may explain why the recorded video is cut short by minutes rather than seconds.

**Comment by jasaw** [comment] 2017-09-12 05:40
@Mr-Dave We need to fix a few things before codec draining can happen.

1. Remove manual setting of encoded packet keyframe. PR #502.
2. Decouple `avcodec_receive_packet` and `avcodec_send_frame`.
3. Finally, we can drain the codec properly.

**Comment by Mr-Dave** [comment] 2017-09-13 00:34
Note that for `Decouple avcodec_receive_packet and avcodec_send_frame.' since the application must support older versions of libav as well as ffmpeg, the approach that we will be looking for is to create a new drain function and NOT to spit apart the existing function which has both of these.  

With respect to the setting of the keyframe in PR #502, I am unclear on why it is necessary to remove this.  This was added for some of the historical versions of libav and ffmpeg.  I will have to check some of the history on which codec's dictated adding it.

Finally, although you may see the issue with the omx decoder, I would be curious as to whether you see the shortened videos with the supported libav / ffmpeg container/codecs that all the other users would be using and reporting.

**Comment by jasaw** [comment] 2017-09-13 05:26
The splitting of avcodec send and receive only makes sense for the new API, which is `avcodec_send_frame` and `avcodec_receive_packet`. The older API `avcodec_encode_video2` and `avcodec_encode_video` will not change. Draining codec with the new API requires one call to `avcodec_send_frame` and loop `avcodec_receive_packet` until AVERROR_EOF, i.e. decoupled send and receive.

Without removing the forced keyframe, every packet during the draining state may potentially be marked as keyframe, which is obviously wrong. Can you please check why keyframe was forced in the first place because it doesn't make sense to randomly mark an encoded packet as keyframe.

**Comment by jasaw** [comment] 2017-09-18 05:39
@Mr-Dave Regarding the forced keyframe, it's only needed for the old ffmpeg interface `avcodec_encode_video` because it does not manipulate AVPacket. In this case, we need to fill in AVPacket manually.

I have updated PR #502 accordingly.

**Comment by Mr-Dave** [comment] 2017-10-29 02:16
I believe this issue should be closed by latest commits which add a flush function upon closing.

**Comment by jasaw** [comment] 2017-10-30 00:09
Why are we not flushing codec if it's timelapse?
Also, why are we not flushing codec for older ffmpeg libraries?
Just trying to understand, any reason why we are not decoupling avcodec send and receive?

**Comment by Mr-Dave** [comment] 2017-10-30 00:49
Timelapse actually gets flushed every FRAME via the return code = -2 and looping on the up to 50 tries.  This is so we can make sure to capture that image in the video considering the next frame could be hours in the future.  

The old versions of ffmpeg did not have the send/receive packet and therefore, there isn't really a flushing other than just closing the file.

The primary reason not decoupling was that I want to keep the flushing activity separate from the regular send / recieve encoding and having the encode somewhat in sync with the older versions.  Within the RTSP code, there was a decoupling attempt which was invoking a flush at each image which isn't right and it cascaded to various problems with all the older versions of ffmpeg and libav. It seemed simpler to just add a flush at the end to address the immediate issue.

I may rethink this when there are fewer releases of ffmpeg under the old methods and the distributions with Libav finally go away.  (Or when ffmpeg changes the send/receive apis)

**Comment by jasaw** [comment] 2017-10-30 01:01
> Timelapse actually gets flushed every FRAME via the return code = -2 and looping on the up to 50 tries.

Does this guarantee the codec to be flushed? I haven't read any documentation or code that uses this method of flushing. I think this comes down to codec implementation, i.e. it can't be guaranteed.

> The old versions of ffmpeg did not have the send/receive packet and therefore, there isn't really a flushing other than just closing the file.

I believe the older `avcodec_encode_video2` interface supports flushing too, but I can see it's safer to just leave it out because old ffmpeg should be phased out anyway.

Regarding decoupling, would you prefer me to close PR #517 for now?

**Comment by Mr-Dave** [comment] 2017-10-30 01:16
There is no guarantee on that flushing.  The whole timelapse functionality falls into a category of "don't do that" with the ffmpeg.  Since timelapse only supports two of the very old codec's I haven't encountered any situations in which the frame didn't flush.

Yes, I think you should close the PR (and maybe this issue as well).  I'm trying to clean out the issues and PRs and tidy up for a release.

**Closed** 2017-10-30 01:22 UTC
Labels: enhancement
