### ISSUE TITLE
Buildroot Patch Requirement

### ISSUE THREAD

**Issue by Mr-DaveDev** [Motion-Project/motion#1028] opened 2019-09-30 22:38 UTC
0. Reviewed guide and contributing documents? (Yes/No):**_yes_**
1. version [x.y.z, hash, other]: **_git master as of 20190929_**
2. installed as a package or compiled from sources [deb, rpm, git, other]: **_compiled_**
3. standalone or part of third party [motion, MotionEyeOS, other]: **_standalone_**
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: **_all_**
5. hardware [x86, ARM, other]: **_Buildroot_**
6. operating system [16.04, Stretch, etc, FreeBSD, other]: **_Buildroot_**

Motion no longer compiles under Buildroot.  Buildroot has disabled `autopoint` and replaced it with `/bin/true`

I created two options for Motioneyeos but not sure they would be compatible with the generic buildroot

Option 1:  Eliminate NLS support from Motion. [gist 1](https://gist.github.com/Mr-DaveDev/8363b732ef57aff1caee81decbc66c86) and [gist 2](https://gist.github.com/Mr-DaveDev/4d213af40bb4786c3a51535bf7cc1fdd) illustrate the required changes which were needed for Motioneyeos.

Option 2:  Implement hack to Buildroot methods to manually invoke autopoint and autoreconf.  [gist 3](https://gist.github.com/Mr-DaveDev/904c05ad12a05432a30510ad33f4661a) and [gist 4](https://gist.github.com/Mr-DaveDev/1b4c2b65f1a84fbc107e2b35c9e102aa) illustrate the required revisions similarly for Motioneyeos.

An additional option considered was ` LIBFOO_GETTEXTIZE` but was inappropriate since it changes (and breaks) the Motion code.

@ffontaine  Since you seem to have worked with this platform previously, would you have any suggestions?

**Comment by ffontaine** [comment] 2019-10-01 11:50
The best solution is to set `MOTION_GETTEXTIZE = YES` and removing `po/Makefile.in` from `AC_CONFIG_FILES` in configure.ac. This behavior was already implemented for libuio package (see https://git.buildroot.net/buildroot/tree/package/libuio/0001-configure-remove-po-Makefile.in.patch). Can you give me more details on the build failure you got with gettextize?

**Comment by Mr-DaveDev** [comment] 2019-10-01 12:46
That is it.  The `MOTION_GETTEXTIZE` revises the `configure.ac` by changing the version number, adding a `EXTRA_DIST` and puts in a `po/Makefile.in` regardless of whether one is there before. 

The [mailing list](http://lists.busybox.net/pipermail/buildroot/2017-October/205254.html) indicated it "can never be correct" to use `MOTION_GETTEXTIZE`  but I did not understand the resolution to that thread nor see that a `MOTION_AUTOPOINT` option was ever added.

**Comment by ffontaine** [comment] 2019-10-01 14:36
OK, I'll send a patch in the next few hours to avoid adding `MOTION_GETTEXTIZE` in buildroot. This patch will basically make NLS support optional depending on the availability of `AM_GNU_GETTEXT` macros.

**Comment by ffontaine** [comment] 2019-10-01 18:26
The issue is more difficult than I thought, even adding `<PKG>_AUTOPOINT` to buildroot (as suggested by Arnout in https://patchwork.ozlabs.org/patch/806209) does not work. Indeed, the build fails on:
```
/usr/bin/make motion.pot-update
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.18 but the autoconf macros are from gettext version 0.19
make[3]: *** [Makefile:213: check-macro-version] Error 1
```
The issue is raised by the fact that buildroot uses gettext in version 0.19.8.1 and motion requests 0.18 in the configure.ac.

However, it seems that this is not possible to bump this requirement without breaking build on systems that do not ship this version of gettext yet (https://github.com/Motion-Project/motion/issues/955)

So, when the new release of motion will be released, I think I'll just set `MOTION_GETTEXTIZE` to `YES` and add a non upstreamable patch that remove po/Makefile.in from `AC_CONFIG_FILES`. We'll get more feedback from the other buildroot members at this time.

An other possibility would be that the motion project ships a tarball that already contains the configure script and all the other dependencies to avoid calling autoreconf in buildroot.

**Comment by Mr-DaveDev** [comment] 2019-10-01 23:48
I think Motion will upgrade to 0.19 as the requirement since 14.04 which has the 0.18 version is now at EoL.  But that would just be a temporary solution since it would then break on the next version of `gettext`

Adding the results of the `autoreconf` significantly pollutes everything.  It also causes additional problems because we could no longer keep track of version numbers that users are running.  The Motion version number includes `git` hash / dates so we can trace issues and that is created when `autoreconf` is executed.  If that was the only option, I would be more inclined to just revert the entire code base and pull everything associated NLS out of the project for all platforms and distros.

**Closed** 2020-09-16 23:32 UTC
