### ISSUE TITLE
could "ffmpeg_passthrough" and/or "netcam_highres" make motion-related movies out of sync?

### ISSUE THREAD

**Issue by huafu** [Motion-Project/motion#741] opened 2018-06-25 14:35 UTC
0. Reviewed guide and contributing documents?: **Yes**
1. version: `4.1.1+git20180621-1b32073` 
2. compiled from sources on Lubuntu 18.04 LTS 
3. standalone (but using with **motioneye** [**NOT** motioneyeos])
4. video stream source: `rtsp://user:pass@cip-xxx/live/0/MAIN` (and/or `/SUB`)
5. hardware: **x86_64** (Intel Centrino 2, 4G RAM laptop)
6. operating system: **Lubuntu 18.04 LTS** (kernel `4.15.0-23-generic`)

I have 3 IP cameras configured the same, on the same physical wired network, with `pre_capture 0`, `post_capture 4` and `framerate 4`.
The `netcam_url` is a 4 frames per second rtsp stream (h264, 640x360 CBR of 384bps) while the `netcam_highres` is a 15 frames per second rtsp stream (h264, 1280x720 CBR of 2048bps).
I have `ffmpeg_passthrough on` for each of my 3 cameras.

While motion events seems to be correctly detected, the movies recorded for them seems to be out of sync with the time it has been detected on the low res stream. For example on the first camera the movie will start recording 7s BEFORE the event and end a little bit before the real end of the event, on the 2nd camera it'll record 4s ahead, and on the last 5 seconds too late.

I'll try to see if those delay remains the same after a long run, but could `netcam_highres` and/or `ffmpeg_passthrough` be the cause of those delay? What could make such delays if not?

**Comment by Mr-Dave** [comment] 2018-06-25 22:58
The capturing ahead of the event is actually documented in the [guide](https://rawgit.com/Motion-Project/motion/master/motion_config.html#ffmpeg_passthrough)  The operative word in the description is "few".  The exact number of frames or seconds that are buffered is dependent upon many items such as CPU speed, hard drive throughput, network bandwidth, "I" frame interval, GOP size etc, etc.  So while it was 7 seconds for your setup, it was 1-2 seconds on mine and it will be different for others. This is part of using a passthrough since it is not decoding all the images and needs to find the event frame and then go backwards in the buffer to the previous I frame that it captured and flush the buffer from that point forward.

**Comment by huafu** [comment] 2018-06-26 10:05
Thanks @Mr-Dave, I somehow missed the last part of the doc you're referring to:
> The resulting movie may also include a few extra frames at the start that would not exist if the movie was created without the passthrough option.

I'll try to play with the `framerate` option to see if that changes anything (trying to increase it so that the `few` becomes fewer 😄 ). Tho my computer is dedicated to that, CPU is used "only" at about 30% by motion, can't really say that the busyness of the CPU could cause such delays 😕 isn't it?

**Comment by Mr-Dave** [comment] 2018-06-28 02:13
Like I indicated, it is dependent upon a lot of items such as the camera "I" frame rate.  Closing this issue as it seems to be working as intended.

**Closed by Mr-Dave** 2018-06-28 02:13 UTC
