### ISSUE TITLE
Web Snapshot

### ISSUE THREAD

**Issue by edasque** [Motion-Project/motion#717] opened 2018-05-21 14:42 UTC
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.11
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: Rpi Camera
5. hardware [x86, ARM, other]: Raspberry Pi 3B - ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Jessie

If I understand correctly the page at the stream_port is a small HTML file that constantly changes the image. Is there a way to access a page which simply gives you the latest at the time of the HTTP request and doesn't refresh, a web snapshot if you will, versus something that triggers saving on disk. Something that basically grabs lastsnap.jpg

Thank you for your response in advance.

**Comment by Mr-Dave** [comment] 2018-06-06 23:35
This appears to be a duplicate of #526 (Provide a single image instead of a MJPEG stream)

**Closed by Mr-Dave** 2018-06-06 23:35 UTC
