### ISSUE TITLE
framerate timelapse movie same as motion detection movies

### ISSUE THREAD

**Issue by hvdwolf** [Motion-Project/motion#507] opened 2017-09-19 04:38 UTC
1. version: 4.0.1 
2. installed release with dpkg -i
3. standalone motion
4. video stream source: V4L Logitech C905 USB webam
5. hardware ARM raspberrypi 3
6. operating system: raspbian jessie lite
7. ffmpeg version 2.6.9 from distribution

I updated 2 weeks ago from the normal jessie lite distribution 3.2.12 to the current 4.0.1 from the github release.
I needed to change some variables in the motion.conf, but further it works OK.
I save motion detected movies at 5 fps, and try to save timelapse movies at ½ fps.

Some relevant settings:
```
ffmpeg_video_codec mpeg4

# Maximum number of frames to be captured per second.
# Valid range: 2-100. Default: 100 (almost no limit).
framerate 5

# Use ffmpeg to encode a timelapse movie
# Default value 0 = off - else save frame every Nth second
ffmpeg_timelapse 2
```

With 3.2.12 my timelapse movies were ½ fps.
With 4.0.1 my timelapse movies are 5 fps. The same framerate as my motion detected movies.

**Comment by tosiara** [comment] 2017-09-20 10:19
I think, timelapse FPS should match ffmpeg's FPS. Because it shares both framerate and bitrate settings with ffmpeg movies. At least on my set up it does match:
```
$ grep framerate motion.conf | head -n 1
framerate 10

$ mediainfo 20170911-timelapse.mpg | grep fps
Frame rate                               : 10.000 fps
```
Maybe someone else can comment on what are the timelapse's expected framerate and bitrate

**Comment by hvdwolf** [comment] 2017-09-20 11:09
Yes, it does match in the current versions. That is exactly the bug and the problem. It used to be two different framerates and for a very good reason. You might want a 24 hour constant timelapse at a bitrate of ½ fps (like I had on 3.2.12) with motion detection at (much) higher frame rates.

That's why I included both settings from the motion.conf in my first post. You only grepped the framerate, you didn't grep the ffmpeg_timelapse. This is really an additional ffmpeg parameter in there for many years already.

That is also exactly why there are two parameters: one parameter describing the fps for movies, and one parameter for timelapse movies
I really consider this as a bug and I'm really doubting to go back to 3.2. I was alarmed because my SD-card was suddenly flooded with timelapse movies that were approx. 5 times as big.

_(Off topic and requiring a new post: I checked with mpeg encoding using the "ffmpeg_video_codec mpg" as described in the documentation, to see whether that one functions correctly with timelapse. That has the same faulty full frame rate AND an extra bug as timelapse movies are created but motion dection movies complain about an "unsupported mpg" codec and are not created)_

**Comment by tosiara** [comment] 2017-09-20 11:21
So would it be fine for you if there were separate config options to control timelapse framerate, bitrate and codec?

**Comment by hvdwolf** [comment] 2017-09-20 11:58
Yes, that would be very nice if you could implement that.
Restoring the "old" behaviour would already be nice, but your proposed implementation is great.

One of my streams is a webcam. It is the least stable input crashing once and sometimes twice a week.
using mpeg4 as coded (on RPI3) for both motion detection and timelapse movie, this would mean a fresh timelapse movie on restart.
I now select mpeg4 as output for my motion detection movies as ffmpeg mpeg4 output is almost as fast as mjpeg (which counts on an RPi3), but much smaller.
If I could select mpg for timelapse movies and the webcam crashes again, the following frames can simply be added in such a mjpeg based timelapse movie (as the documentation also describes). Afterwards (crontab job) I could simply convert the mpeg movie to an h264 streaming mp4 (like I always did)

**Comment by tosiara** [comment] 2017-09-20 12:01
Ok, so then it's a duplicate of https://github.com/Motion-Project/motion/issues/43
Please comment there

**Closed by tosiara** 2017-09-20 12:01 UTC

**Comment by hvdwolf** [comment] 2017-09-20 13:59
No, this is not a duplicate. I was filing a bug report: Something that worked in 3.2.12 AND is still [literally mentioned](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#ffmpeg_timelapse_mode) in the 4.0.1 (and above) documentation, does no longer work. By carefully "seducing" me to even better functionality, you change my bug report into a feature request.

Your issue [#43](Separate options for timelapse and movies) is a feature request. Based on all IT standards (and let's take ITIL as big example), an incident (bug) is something different then a change request, and requires different attention.

**Comment by jasaw** [comment] 2017-09-21 00:16
From the config file comment, it suggests that timelapse is independent of the capture framerate. It also suggests that maximum timelapse framerate is 1 fps.
```
# Use ffmpeg to encode a timelapse movie
# Default value 0 = off - else save frame every Nth second
ffmpeg_timelapse 0
```

If you look at the capture framerate config comment, the minimum framerate is 2 fps.
```
# Maximum number of frames to be captured per second.
# Valid range: 2-100. Default: 100 (almost no limit).
framerate 2
```

Forcing the timelapse framerate to minimum of 2 fps, the same as capture framerate, is wrong according to motion's documentation.

I have to agree with @hvdwolf on this one.

**Comment by Mr-Dave** [comment] 2017-09-21 00:20
Motion is doing this correctly.  It is capturing images at the rate specified in the timelapse and creating the movies at the requested frame rate in the configuration file.  The frame rate of the resulting movie can NOT and should not be based upon the rate of capture of the images for timelapse.

**Comment by hvdwolf** [comment] 2017-09-21 08:31
We should make a distinction here.
ffmpeg is set with a framerate of for example 25 fps (for motion detection).
If I have a USB webcam on a (shared) USB connection on my RPi, I can capture up to a maximum of 5 fps. Simply because the (shared) USB connection is flooded on the RPi.
The result will be a motion detection movie with a framerate of 25 fps (as set) and as can be displayed from a "ffmpeg -i" or "mediainfo" check, but the real framerate is 5fps tops.

Also vice-versa: If I set an fps of 5 for motion detection, and a ffmpeg_timelapse of 2 (which is 1 frame per 2 seconds -> ½ fps), my resulting timelapse movie will mention a 5 fps rate, but only having 1 frame 
per 2 seconds.
This has always been the case. I'm running motion already for years and years, with 3.2.12 for a quite lengthy period, and now since 2 weeks (or so) on motion 4.0.1 the **real stored** framerate of the timelapse movie is the same  as that of the motion detection movie.

I programmed in C in 1993 for the very last time, otherwise I would do my best to deliver a pull request to you

**Comment by tosiara** [comment] 2017-09-21 08:34
Real fps is calculated by motion and ffmpeg movie fps will be adjusted to real fps at runtime

**Comment by hvdwolf** [comment] 2017-09-21 09:27
OK, I might be wrong. I also do straight capturing, saving and streaming with ffmpeg and clvc. Maybe I mix up the details.

Anyway, In 3.2.12 and before the "ffmpeg_timelapse 2" did produce timelapse movies with the specified 1 frame per 2 seconds. 
Currently, as a workaround, I can of course disable timelapse from motion run a separate cvlc or ffmpeg process via the "[use_extpipe](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#use_extpipe)" and ext_pipe variables.

**Comment by tosiara** [comment] 2017-09-21 09:59
The thing is that the amount of frames that are being written into the file has not changed since 3.2. It is still the same, it's only metadata of the video file that specifies different fps. You can always change fps of the resulting timelapse file using lossless remux and you will get the "old" frame rate. Just for the reference, when I play MPG timelapse through VLC - the speed is much higher than the reported fps. However, ffplay plays them fine in exact 10 fps.

The issue with changed file size is probably related to codec params that were updated. Have you noticed any difference in encoder flags in mediainfo when comparing old and new timelapse

**Comment by hvdwolf** [comment] 2017-09-21 21:20
I don't need to look at encoding parameters. I gave an example where I counted the frames for a file. I also mentioned that the files were much bigger.

I already made a work around.
One of the big advantages of 4.0.1 is the availability of the x264 encoding algorithm. I now encode them as x264. For motion detection that works fine, for timelapse it automatically makes mpeg4 movies (not x264 so feature request 43 is already partially dealt with).
One of the "issues" with all the encoding formats, apart from swf which is hardly browser supported anymore, is that the encoded formats are not in streaming format 
On the "on_movie_end" event I already had a script running, using the "-movflags faststart" to "moving the moov atom to the beginning of the file" to make it usable for streaming, so now I have:
```
#!/bin/bash

filmpje="$1"

# As I have the idea that movie "closure" and the start of ffmpeg is too close upon each other we wait 5 seconds
sleep 5

#movie is created in x264 movie format but is not in streaming format, so use the "-movflags faststart" option

if [[ "$filmpje" != "*timelapse*" ]]  #check if timelapse is in the name -> else statement
then
        ffmpeg -i "$filmpje" -c:v copy -movflags faststart  -f mp4 /opt/motion/tmp/$(basename $filmpje)
        rsync -P /opt/motion/tmp/$(basename $filmpje) /media/motion
        sleep 3
        rm -f /opt/motion/tmp/$(basename $filmpje)
else
        # Only for the full timelapse movie which also has the avi extension
        ffmpeg -i "$filmpje" -c:v libx264 -threads 2 -crf 23 -preset faster -movflags faststart -r 1  -f mp4 /opt/motion/tmp/$(basename ${filmpje%avi}mp4)
        rsync -P /opt/motion/tmp/$(basename ${filmpje%avi}mp4) /media/motion
        sleep 3
        rm -f /opt/motion/tmp/$(basename ${filmpje%avi}mp4)
fi
```
So my motion detection movies are 5 fps (my setting) and my timelapse movie is 1 fps and both can be streamed from my /media/motion share whihis available on my centralwebserver..

(the "-movflags faststart" as option for x264 might be a nice feature request to make the video "streaming enabled" by default)

A cron job (was already running) automatically removes the originals after x days (depending on the type of movie)
