### ISSUE TITLE
Dependency check missing in builddeb.sh

### ISSUE THREAD

**Issue by gusarg81** [Motion-Project/motion#1181] opened 2020-08-01 16:55 UTC
Hi,

This script is missing dependency check for fakeroot, which is necessary to build a deb package. Is why fails to build (even when It ends with "no errors", but checking in the script log you will see the error about fakeroot).

**Comment by tosiara** [comment] 2020-08-04 14:20
Is it a duplicate of https://github.com/Motion-Project/motion-packaging/issues/9 ?

**Comment by gusarg81** [comment] 2020-08-04 14:23
Yes, indeed!

**Closed** 2020-08-04 14:23 UTC
