### ISSUE TITLE
v4l2_set_mmap: Error requesting buffers 4 for memory map. VIDIOC_REQBUFS:

### ISSUE THREAD

**Issue by barsznica** [Motion-Project/motion#519] opened 2017-10-19 12:22 UTC
Thank you for such a complete, versatile and awesome package.
I love the multi camera ability and the degree of configuration.

It often work for days, but eventually I get the gray screen, with the attached errors.
Any ideas?

1. version: ?
2. installed as a package: Deb
3. standalone: motion 
4. video stream source: V4L USB
5. hardware: ARM (RPi) 
6. operating system: Linux (Deb)

I have had this posted [here](https://stackoverflow.com/questions/44493337/motion-v4l2-set-mmap-error-requesting-buffers-4-for-memory-map-vidioc-reqbufs) for a while.
![motionstart](https://user-images.githubusercontent.com/11470190/31770570-1cd05798-b520-11e7-9ace-935a9b98ab5d.PNG)
![motiondies](https://user-images.githubusercontent.com/11470190/31770571-1eb5ef82-b520-11e7-8087-8dfdc386827c.PNG)

**Comment by Mr-Dave** [comment] 2017-10-22 16:01
The first thing that I would recommend is making sure you are running the "Stretch" version of Debian.  The error listed is a result of a call to the driver software and the most recent release may update that driver software.  If the error still exists after the upgrade, you would need to download and build the latest source code to ensure that the problem still exists in our current code base.

**Comment by Mr-Dave** [comment] 2017-10-29 03:00
Closing issue as it relates to a old version.  If the issue is replicated using the current master code and the most current Debian version, please re-open with revised logs.

**Closed by Mr-Dave** 2017-10-29 03:00 UTC

**Comment by barsznica** [comment] 2017-10-31 10:56
Thanks, I was using an old version.
I have installed the current compiled package and everything is going very well.
Thanks again for this awesome software!!!

**Comment by barsznica** [comment] 2017-11-04 06:41
PiZeroW has stopped responding to the two Logitech cams I have ( most likely, the other way around ;} ), after about a week _rock steady_ on one of them, weird?
MS Webcam running rock steady for, also, a week, on a Pi1 and works fine on the PiZeroW (as a test).
Just snatched a MS cam off eBay and will probably stick to these; although, I have not had much experience with "newer" Logitech cams.
It's probably just there rubbish cams!
Will update

BTW:
Not as much debug info as the previous versions! :)
I know, there are instructions, but ...
I'm countin' down the days till I get my VFD "days till I'm 65" display going...
(hint 1: need 4 digits. hint 2: hint 1 is not much of a hint!)

**Comment by barsznica** [comment] 2017-11-26 11:26
Have had both systems running with Microsoft cams for about 2 weeks now, without a hitch!

FYI: 1 is a MS LifeCam VX-1000 [model 1080, 500mA]. Other is LifeCam VX-2000 [model 1381, 500mA].

The dodgy LogiTech units are:
 V-UBB39 [PN: 861224-0000, PID: LZ752B8, 100mA],
V-UBQ42 [PN: 860-000091, PID: LZ839B6, 100mA] and
1 without a label.
![imag1024](https://user-images.githubusercontent.com/11470190/33239569-797489c8-d2f4-11e7-9c77-5e123589b566.jpg)
![imag1023](https://user-images.githubusercontent.com/11470190/33239570-79afa986-d2f4-11e7-8702-92c6badb2b5d.jpg)


I will test out the V-UBU4P [860-000231, PID: LZ933BP, 500mA, CarlZeiss, AutoFocus] soon, but looking at the PIDs, I'm fairly confident it will start playing up after a week or two...
![imag1021](https://user-images.githubusercontent.com/11470190/33239571-804f2b4a-d2f4-11e7-8492-e4506f4fb3d9.jpg)
![imag1022](https://user-images.githubusercontent.com/11470190/33239572-80b81bfa-d2f4-11e7-81c4-565f86f54bc4.jpg)

**Comment by tosiara** [comment] 2017-11-26 13:34
I have 3 Logitech C905 ("car zeiss auto focus") running motion fine. Note that the same camera may come with different hardware and different vid:pid:
046d:080a Logitech, Inc. Portable Webcam C905
046d:0991 Logitech, Inc. QuickCam Pro for Notebooks

**Comment by barsznica** [comment] 2017-11-27 12:30
Damn it! 
The VX-1000 had become unresponsive when I was posting how well it was doing!!! :(
![fail](https://user-images.githubusercontent.com/11470190/33266717-b1dad09c-d3c6-11e7-8a56-d153d80ed8f4.PNG)

**Comment by barsznica** [comment] 2018-10-17 14:40
The V-UBU4P [860-000231, PID: LZ933BP, 500mA, CarlZeiss, AutoFocus] (mentioned and pictured above) had been flawless, but I still get the error with the dodgy LogiTech units (mentioned and pictured above).
I hope zeph's solution works!

**Comment by zeph** [comment] 2018-10-17 16:29
@barsznica the other trick is to plug in a usbstick and partition it in a way that you can have a swap space ;)

**Comment by barsznica** [comment] 2018-10-17 22:21
zeph, I don't think a USB swap is necessary, as I don't seem to be maxing-out the RAM (3 cams & Node-RED on Pi3, 3 cams on Orange Pi PC Plus and 1 on Pi0W/Pi1).

**Comment by barsznica** [comment] 2018-10-17 22:55
@zeph, OK, I will, but I'm more interested in your other solution ;)

**Comment by Mr-Dave** [comment] 2018-10-18 00:29
@zeph This issue is a "Not running current version" problem.  If you're not running the current version, I would indicate that the resolution is the same.  If you are however running the current master branch then that would be something different.  The support page as well as the issue template indicates the things that would be needed in order to investigate/resolve it.  e.g. Full uncut log at the INF level from start to the issue, version including git date and hash, etc.

I'd add that if you want to adjust the MMAP buffers requested it is specified at top of `video_v4l2.c`.   Motion requests 4 buffers from the driver and whatever the driver reports back Motion as being possible is what is used.

**Comment by barsznica** [comment] 2018-10-18 13:19
I was running version 4.0

**Comment by barsznica** [comment] 2018-10-19 14:20
> I have 3 Logitech C905 ("car zeiss auto focus") running motion fine. Note that the same camera may come with different hardware and different vid:pid:
> 046d:080a Logitech, Inc. Portable Webcam C905
> 046d:0991 Logitech, Inc. QuickCam Pro for Notebooks

Cool, running `lsusb` yielded "ID 046d:080a Logitech, Inc. Portable Webcam C905"

**Comment by fcastroruiz** [comment] 2019-03-08 09:35
@electron1979 i have the same issue, can you explain best how you solved it? thnks

**Comment by electron1979** [comment] 2019-03-08 23:18
I didn't solve it. I just stopped using the 3rd camera, which was one of the dodgy ones I refer to here,  https://github.com/Motion-Project/motion/issues/519#issuecomment-347001740

So I'm not sure if the problem is running more than 2 USB cameras or the dodgy cameras themselves

**Comment by fcastroruiz** [comment] 2019-03-11 07:25
> So I'm not sure if the problem is running more than 2 USB cameras or the dodgy cameras themselves

The problem is not running more than 2 USB cameras, i have only one, and i have the same issue.

thanks for your reply
