### ISSUE TITLE
Too many open files. Motion service holding open deleted files.

### ISSUE THREAD

**Issue by adjenks** [Motion-Project/motion#1552] opened 2022-07-04 02:53 UTC
### Did you read the guide?

Yes

### What is the base version number of Motion being used?

4.2.x

### What was the install method?

Installed via package tool

### What is base architecture?

x86

### What is the distro being used?

Ubuntu

### Disto version number

20.04

### Camera type(s) being used?

v4l2 USB camera

### Describe the issue/problem and steps to reproduce

The motion service holds open deleted files and this maxes out the number of open files on linux (default 1024), and then motion is unable to output more files.
I have a process that deletes the files after copying them somewhere, perhaps it deleted them before motion was done closing them and this interfered? Motion should always close files anyways though.
It took a long time for the service to fail because it had built up many open files slowly.

I will just periodically restart the service in the meantime.

### Relevant Motion log output (at log_level 8)

```shell
> tail /var/log/motion/motion.log
> [1:ml1] [NTC] [ALL] [Jul 04 02:27:48] motion_detected: Motion detected - starting event 386692
> [1:ml1] [NTC] [ALL] [Jul 04 02:27:52] mlp_actions: End of event 386692
> [1:ml1] [ERR] [ENC] [Jul 04 02:27:52] ffmpeg_set_outputfile: Error opening file /mnt/motionramdisk/xxxx.mkv: Too many open files
> [1:ml1] [ERR] [ENC] [Jul 04 02:27:52] ffmpeg_open: Could not set the stream
> [1:ml1] [ERR] [EVT] [Jul 04 02:27:52] event_ffmpeg_newfile: Error opening context for movie output.

Unfortunately I restarted the service before capturing more verbose logs.

> lsof -p 12345
> truncated...
> motion  185711 motion   71w   REG   0,51        0      585 /mnt/motionramdisk/0-163508-20220323112741.mkv (deleted)
> motion  185711 motion   72w   REG   0,51        0      586 /mnt/motionramdisk/0-163510-20220323112749.mkv (deleted)
> motion  185711 motion   73w   REG   0,51        0      587 /mnt/motionramdisk/0-163512-20220323112757.mkv (deleted)
> motion  185711 motion   74w   REG   0,51        0      588 /mnt/motionramdisk/0-163513-20220323112801.mkv (deleted)
> motion  185711 motion   75w   REG   0,51        0       63 /mnt/motionramdisk/0-163517-20220323112819.mkv (deleted)
> truncated.....
```

**Comment by Mr-Dave** [comment] 2022-07-05 00:49
The deletion of files that are in the process of being created is the root cause.  Since Motion is following the standard method of the ffmpeg libs to close files, I'm going to close this as "won't fix".  If you would like to research and create a pull request to somehow close the files differently, we'll review.

**Closed by Mr-Dave** 2022-07-05 00:49 UTC
Labels: bug

**Comment by adjenks** [comment] 2022-07-06 00:55
Alright.
