### ISSUE TITLE
NULL pointer dereference in netcam_read_next_header

### ISSUE THREAD

**Issue by ygrishin** [Motion-Project/motion#389] opened 2017-05-22 05:55 UTC
[CoreDump.zip](https://github.com/Motion-Project/motion/files/1017860/CoreDump.zip)
Happens in motion 4.0.1-1 (amd64) but was seen initially on Motion 3.2.12+git20140228.
I am using Kubuntu 16.04.2 LTS amd64.

$uname -a
Linux recorder 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$cat /var/log/syslog
...
May 21 23:21:14 recorder motion: [0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motion/motion.conf
May 21 23:21:14 recorder motion: [0:motion] [ALR] [ALL] conf_cmdparse: Unknown config option "ffmpeg_deinterlace"
May 21 23:21:14 recorder motion: [0:motion] [ALR] [ALL] conf_cmdparse: Unknown config option "sdl_threadnr"
May 21 23:21:14 recorder motion: [0:motion] [WRN] [ALL] thread config option deprecated use camera
May 21 23:21:14 recorder motion: [0:motion] [NTC] [ALL] config_camera: Processing camera config file /etc/motion/thread1.conf
May 21 23:21:14 recorder motion: [0:motion] [NTC] [ALL] motion_startup: Motion 4.0.1 Started
May 21 23:21:14 recorder motion: [0:motion] [NTC] [ALL] motion_startup: Logging to file (/var/log/motion/motion.log)
May 21 23:21:14 recorder kernel: [49437.909642] ml1[3031]: segfault at 0 ip 00007f7e5cf8a4c9 sp 00007f7e4ea8e9f0 error 4 in libc-2.23.so[7f7e5cefd000+1bf000]
May 21 23:21:15 recorder org.kde.KScreen[1258]: kscreen: Primary output changed from KScreen::Output(Id: 66 , Name: "VGA1" ) ( "VGA1" ) to KScreen::Output(Id: 66 , Name: "VGA1" ) ( "VGA1" )
May 21 23:23:08 recorder org.kde.KScreen[1258]: message repeated 35 times: [ kscreen: Primary output changed from KScreen::Output(Id: 66 , Name: "VGA1" ) ( "VGA1" ) to KScreen::Output(Id: 66 , Name: "VGA1" ) ( "VGA1" )]
May 21 23:23:11 recorder motion: [0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motion/motion.conf
May 21 23:23:11 recorder motion: [0:motion] [ALR] [ALL] conf_cmdparse: Unknown config option "ffmpeg_deinterlace"
May 21 23:23:11 recorder motion: [0:motion] [ALR] [ALL] conf_cmdparse: Unknown config option "sdl_threadnr"
May 21 23:23:11 recorder motion: [0:motion] [WRN] [ALL] thread config option deprecated use camera
May 21 23:23:11 recorder motion: [0:motion] [NTC] [ALL] config_camera: Processing camera config file /etc/motion/thread1.conf
May 21 23:23:11 recorder motion: [0:motion] [NTC] [ALL] motion_startup: Motion 4.0.1 Started
May 21 23:23:11 recorder motion: [0:motion] [NTC] [ALL] motion_startup: Logging to file (/var/log/motion/motion.log)
May 21 23:23:11 recorder kernel: [49554.955243] ml1[3049]: segfault at 0 ip 00007efd4a8e44c9 sp 00007efd3c3e89f0 error 4 in libc-2.23.so[7efd4a857000+1bf000]
...

$tail -n 200 /var/log/motion/motion.log (camera's IP address was blacked out):
...
[0:motion] [NTC] [ALL] [May 21 23:23:11] motion_startup: Using log type (ALL) log level (NTC)
[0:motion] [NTC] [ENC] [May 21 23:23:11] ffmpeg_init: ffmpeg libavcodec version 56.60.100 libavformat version 56.40.101
[0:motion] [NTC] [ALL] [May 21 23:23:11] main: Motion running in setup mode.
[0:motion] [NTC] [ALL] [May 21 23:23:11] main: Camera 1 is from /etc/motion/thread1.conf
[0:motion] [NTC] [ALL] [May 21 23:23:11] main: Camera 1 is device: http://A.B.C.D/nphMotionJpeg?Resolution=1280x720&Quality=Standard input -1
[0:motion] [NTC] [ALL] [May 21 23:23:11] main: Stream port 8081
[0:motion] [NTC] [ALL] [May 21 23:23:11] main: Waiting for threads to finish, pid: 3048
[1:ml1] [NTC] [ALL] [May 21 23:23:11] motion_init: Camera 1 started: motion detection Enabled
[1:ml1] [ALR] [NET] [May 21 23:23:11] netcam_start: Network Camera thread starting... for url (http://A.B.C.D/nphMotionJpeg?Resolution=1280x720&Quality=Standard)
[1:ml1] [NTC] [NET] [May 21 23:23:11] netcam_read_first_header: Found Conn: close header ('Connection: close')
[0:motion] [NTC] [ALL] [May 21 23:26:04] motion_startup: Using log type (ALL) log level (NTC)
[0:motion] [NTC] [ENC] [May 21 23:26:04] ffmpeg_init: ffmpeg libavcodec version 56.60.100 libavformat version 56.40.101
[0:motion] [NTC] [ALL] [May 21 23:26:04] main: Motion running in setup mode.
[0:motion] [NTC] [ALL] [May 21 23:26:04] main: Camera 1 is from /etc/motion/thread1.conf
[0:motion] [NTC] [ALL] [May 21 23:26:04] main: Camera 1 is device: http://A.B.C.D/nphMotionJpeg?Resolution=1280x720&Quality=Standard input -1
[0:motion] [NTC] [ALL] [May 21 23:26:04] main: Stream port 8081
[0:motion] [NTC] [ALL] [May 21 23:26:04] main: Waiting for threads to finish, pid: 3075
[1:ml1] [NTC] [ALL] [May 21 23:26:04] motion_init: Camera 1 started: motion detection Enabled
[1:ml1] [ALR] [NET] [May 21 23:26:04] netcam_start: Network Camera thread starting... for url (http://A.B.C.D/nphMotionJpeg?Resolution=1280x720&Quality=Standard)
[1:ml1] [NTC] [NET] [May 21 23:26:04] netcam_read_first_header: Found Conn: close header ('Connection: close')
...

Command was run when the crash happened:
#/usr/bin/motion -s
as well as it happens with
#/etc/init.d/motion start

Camera in question: Panasonic BL-VP104W. Apparently supports MJPEG since I am able to get the video when open http://A.B.C.D/nphMotionJpeg?Resolution=1280x720&Quality=Standard in browser.

Core dump is attached.

**Comment by tosiara** [comment] 2017-05-22 07:02
Please update to the latest version

**Comment by ygrishin** [comment] 2017-05-22 16:02
motion 4.0.1+gitc50d4b5 doesn't crash. Thanks.

**Comment by ygrishin** [comment] 2017-05-22 16:52
I am able to reproduce the crash eventually, attaching the core dump along with the binary.
[motion-4.0.1+gitc50d4b5.core.zip](https://github.com/Motion-Project/motion/files/1019579/motion-4.0.1.gitc50d4b5.core.zip)

**Comment by jogu** [comment] 2017-05-22 18:32
I can't see how the crash can be due to a missing strstr.c.

Can you open the binary and core file in gdb and run 'thread apply all bt' and paste the entire output of that command into a gist and add the link here please?

**Comment by ygrishin** [comment] 2017-05-22 22:27
There you go https://gist.github.com/ygrishin/467bb6889aaab0b01b07abf7d42d48a9#file-motion-3-2-12-git20140228-4-b3-gdb-output
Though I don't have that Ubuntu environment anymore. This time it's Debian 8.8 amd64 with libc-2.19.so and motion 3.2.12-git20140228-4-b3, same story again. I suspect it's specific to my camera.

**Comment by tosiara** [comment] 2017-05-23 10:56
Can you reproduce and get stack with the latest version?
3.2.12 is an ancient version. A lot of fixes committed since that

**Comment by ygrishin** [comment] 2017-05-25 03:45
Will do.

**Comment by ygrishin** [comment] 2017-06-15 00:59
There you go https://gist.github.com/ygrishin/070ef82d661f2de4f67cd0b3317fe2d9. Let me know if anything else is needed because I want to dump this environment soon.

**Comment by jogu** [comment] 2017-06-15 11:22
Thanks, that's helpful. The line it seems to be crashing at is this one:

            retval = (strstr(header, netcam->boundary) == NULL);

within netcam_read_next_header. netcam->boundary is NULL, and it's not valid to pass NULL to strstr.

I suspect it'll be something specific to your camera that is causing motion to have difficultly parsing the stream. Which camera are you using?

**Comment by ygrishin** [comment] 2017-06-16 02:12
Panasonic BL-VP104WP connected over ethernet.

**Comment by tosiara** [comment] 2017-06-20 12:25
@jogu do you know if it is possible to get http mjpeg stream through the rtsp code as it was done with v4l:// protocol? Would be nice so we can deprecate internal mjpeg http parsing

**Comment by iskunk** [comment] 2017-06-20 20:08
@tosiara: In principal, it's supposed to work, but I've only tried it in my tree. The netcam URL needs to start with `mjpeg://`, and the port number has to be specified even if it's 80.

Would be interesting to see what headers this camera is sending out, as it appears to be a corner case that we're not handling. But deprecating functionality that is duplicated in FFmpeg is ultimately the right way to go.

**Comment by tosiara** [comment] 2017-06-21 07:16
@ygrishin can you try to change your config so the netcam url is set to:
`mjpeg://A.B.C.D:80/nphMotionJpeg?Resolution=1280x720&Quality=Standard`

**Comment by ygrishin** [comment] 2017-06-25 23:12
I confirm that it works as expected (no crash) with `mjpeg://A.B.C.D:80/nphMotionJpeg?Resolution=1280x720&Quality=Standard`.

**Closed** 2017-08-31 00:44 UTC
Labels: bug
